In [68]:
pdf_file_path = "grammar_books/kalamang.pdf"

In [69]:
import json
import pymupdf
import collections
import numpy as np
import re
from tqdm import tqdm

In [8]:
def extract_visual_lines(page):

    spans = []
    blocks = page.get_text("dict")["blocks"]

    for block in blocks:
        for line in block.get("lines", []):
            for span in line.get("spans", []):
                sb = span["bbox"]
                spans.append({
                    "text": span["text"],
                    "x0": sb[0],
                    "y0": sb[1],
                    "x1": sb[2],
                    "y1": sb[3],
                    "font": span.get("font"),
                    "size": span.get("size"),
                    "block": block,  # optional
                })

    spans = sorted(spans, key=lambda s: s["y0"])
    if len(spans)==0:
        return None

    # Dynamic tolerance based on median height
    heights = [s["y1"] - s["y0"] for s in spans]
    median_h = np.median(heights) if heights else 10
    Y_TOL = median_h * 0.4

    visual_lines = []
    current_line = [spans[0]]

    for prev, curr in zip(spans, spans[1:]):
        if abs(curr["y0"] - prev["y0"]) < Y_TOL:
            current_line.append(curr)
        else:
            visual_lines.append(current_line)
            
            current_line = [curr]

    visual_lines.append(current_line)

    # Merge and sort spans within each line
    merged_lines = []
    for line_spans in visual_lines:
        sorted_spans = sorted(line_spans, key=lambda s: s["x0"])
        merged_text = " ".join([s["text"] for s in sorted_spans if s["text"].strip()])
        # Get most common font size and style by length weighting
        font_sizes = {}
        font_styles = {}
        for s in sorted_spans:
            length = len(s["text"])
            font_key = (s["font"], s["size"])
            font_sizes[font_key] = font_sizes.get(font_key, 0) + length
            font_styles[s["font"]] = font_styles.get(s["font"], 0) + length
        
        if font_sizes:
            common_font_size = max(font_sizes, key=font_sizes.get)
        else:
            common_font_size = (None, None)

        if font_styles:
            common_font_style = max(font_styles, key=font_styles.get)
        else:
            common_font_style = None

        
            
        
        merged_lines.append({
            "text": merged_text,
            "spans": sorted_spans,
            "x0": sorted_spans[0]["x0"],
            "y0": np.mean([s["y0"] for s in sorted_spans]),
            "x1": sorted_spans[-1]["x1"],
            "y1": max(s["y1"] for s in sorted_spans),
            "span_count": len(sorted_spans),
            "common_font_size": common_font_size[1],
            "common_font_style": common_font_style,
        })

    return merged_lines

In [71]:
# Load doc
print("Opening PDF file...")
doc = pymupdf.open(pdf_file_path)
print("PDF file opened successfully.")
print("Number of pages in PDF file:", doc.page_count)

Opening PDF file...
PDF file opened successfully.
Number of pages in PDF file: 573

In [72]:

font_size_counts = collections.Counter()
font_style_counts = collections.Counter()

In [73]:
all_merged_lines = []
for page in doc:
    page_num = page.number + 1
    
    merged_lines = extract_visual_lines(page)
    if merged_lines is None:
        continue

    for line in merged_lines:
        # Update font size and style counts
        font_size_counts.update([line["common_font_size"]])
        font_style_counts.update([line["common_font_style"]])
    
    all_merged_lines.append({
        "page_num": page_num,
        "lines": merged_lines
    })

    #for line in merged_lines:
        #print(line["text"], end="|")
    #print("---")
print("Most common font sizes:", font_size_counts.most_common(5))
print("Most common font styles:", font_style_counts.most_common(5))

Most common font sizes: [(10.909099578857422, 17600), (8.966400146484375, 674), (9.962599754333496, 243), (11.9552001953125, 139), (14.346199989318848, 98)]
Most common font styles: [('LibertinusSerif-Regular', 16226), ('LibertinusSerif-Italic', 2190), ('LibertinusSerif-Semibold', 529), ('LinuxLibertineG', 69), ('LibertinusMath-Regular', 27)]

In [74]:
most_common_font_size = font_size_counts.most_common(1)[0][0]
body_text_size = most_common_font_size
print("Determined body text size:", body_text_size)

Determined body text size: 10.909099578857422

In [87]:
# load doc
print("Opening PDF file...")
doc = pymupdf.open(pdf_file_path)   
print("PDF file opened successfully.")
print("Number of pages in PDF file:", doc.page_count)

# Render the pdf with the lines extracted with bounding boxes 

draw_lines = []
import re
odd = True
parallel_start = False
line_no = -1
count_from_start = 0

for row in all_merged_lines:
    page_num = row["page_num"]
    page = doc[page_num - 1]
    if page_num < 19 or (page_num > 80 and page_num < 135):
        continue

    for line in row["lines"]:
        if line["common_font_size"] < body_text_size - 0.1:
            continue
        
        line_no += 1
        # Quick parallel sentenece manual extraction
        bbox = (line["x0"], line["y0"], line["x1"], line["y1"])
        
        text = line["text"].strip().lower()

        # Check if line starts with (n) where n is a number
        if re.match(r"^\(\d+\)", text):
            # Get number inside ()
            number = int(re.findall(r"^\((\d+)\)", text)[0])
            if number > 999:
                continue
            #print(f"Page {page_num}: {line['text']}")
            #print(line["x0"], line["y0"], line["x1"], line["y1"])
            draw_lines.append({
                "page_num": page_num,
                "line_no": line_no,
                "text": line["text"],
                "line": line,
                "bbox": bbox,
                "start": True
            })
            #print("--1--")
            #print(line["common_font_size"], line["common_font_style"])
            parallel_start = True
            rect = pymupdf.Rect(bbox)
            color = (0, 1, 0)  # Green for start
            page.draw_rect(rect, color=color, width=0.5)
            count_from_start = 2
            continue

        # Roughly near 84 or 96 x value
        values = [84,88,90,96,100,108,114,120]
        if count_from_start > 0 and "LibertinusSerif" in line["common_font_style"]:
            #print("--2--")
            #print(line["common_font_size"], line["common_font_style"])
            draw_lines.append({
                "page_num": page_num,
                "line_no": line_no,
                "text": line["text"],
                "line": line,
                "bbox": bbox,
                "start": False
            })
            rect = pymupdf.Rect(bbox)
            color = (1, 0, 1)  # Magenta for continuation
            page.draw_rect(rect, color=color, width=0.5)
            count_from_start -= 1
            continue
        
        if any(abs(line["x0"] - v) < 3 for v in values) and "LibertinusSerif" in line["common_font_style"]:
            # print the line
            #print(f"Page {page_num}: {line['text']}")
            #print("--abs--")
            #print(line["common_font_size"], line["common_font_style"])
            draw_lines.append({
                "page_num": page_num,
                "line_no": line_no,
                "text": line["text"],
                "bbox": bbox,
                "line": line,
            })
            rect = pymupdf.Rect(bbox)
            color = (1, 0, 0) if odd else (0, 0, 1)
            page.draw_rect(rect, color=color, width=0.5)
            odd = not odd
        
        else:
            if parallel_start:
                #print("---")
                #print(f"Page {page_num}: {line['text']}")
                #print(line["x0"], line["y0"], line["x1"], line["y1"])
                pass
            parallel_start = False



doc.save("output_with_lines.pdf")

Opening PDF file...
PDF file opened successfully.
Number of pages in PDF file: 573

In [88]:
# Open the pdf again to draw blocks
print("Opening PDF file...")
doc = pymupdf.open(pdf_file_path)   
print("PDF file opened successfully.")

i = 0
cont_lines = 0
prev_line_no = -1
temp_block = []
final_blocks = []
while(i < len(draw_lines)-1):
    if i==0:
        temp_block.append(draw_lines[i])
        prev_line_no = draw_lines[i]["line_no"]
        i+=1
        continue
    curr_line = draw_lines[i]
    curr_line_no = curr_line["line_no"]
    if curr_line_no == prev_line_no + 1:
        temp_block.append(curr_line)
        prev_line_no = curr_line_no
        i+=1
    else:
        if len(temp_block) >0:
            print("Block:")
            # Check where the start block is
            start_indices = [idx for idx, bline in enumerate(temp_block) if bline.get("start")]
            page_numbers = [bline["page_num"] for bline in temp_block]
            #page_number_bool = [p in range(285, 476) for p in page_numbers]
            #print(page_number_bool)
            if start_indices:
                start_idx = start_indices[0]
                # Use start idx usually ignoring here for romansh as there are many without a (n) starting block
                final_blocks.append(temp_block[start_idx:])
                for bline in temp_block[start_idx:]:
                    print(f"Page {bline['page_num']}: {bline['text']}")
                    page_num = bline["page_num"]
                    page = doc[page_num - 1]
                    rect = pymupdf.Rect(bline["bbox"])
                    color = (0, 1, 0)  # Green for start
                    page.draw_rect(rect, color=color, width=0.5)
                print("-----")
        temp_block = [curr_line]
        prev_line_no = curr_line_no
        print(f"New block starting at line no {curr_line_no}")
        print(f"Current line text: {curr_line['text']}")
        
        i+=1
    
    
doc.save("output_with_lines_filtered.pdf")

Opening PDF file...
PDF file opened successfully.
Block:
New block starting at line no 54
Current line text: (1) hukat kon anggon yuwa
Block:
Page 20: (1) hukat kon anggon yuwa
Page 20: jaring_ikan satu milik_saya ini
Page 20: ‘jaring ikan milik saya satu ini’
-----
New block starting at line no 75
Current line text: (2) kaskas et-eir
Block:
Page 21: (2) kaskas et-eir
Page 21: burung_camar hidup-dua
Page 21: ‘dua burung camar’
-----
New block starting at line no 107
Current line text: (3) ma se guru
Block:
Page 22: (3) ma se guru
Page 22: dia sudah guru
Page 22: ‘Dia sudah (menjadi seorang) guru.’
Page 22: (4) ma me
Page 22: dia itu
Page 22: ‘Itu dia.’
Page 22: (5) im kansuor
Page 22: pisang empat
Page 22: ‘Ada empat pisang.’
-----
New block starting at line no 128
Current line text: (6) ka-mun narabir-in
Block:
Page 22: (6) ka-mun narabir-in
Page 22: kamu-jangan berteriak-jangan
Page 22: ‘Janganlah kamu berteriak!’
-----
New block starting at line no 150
Current line text: (7) an me watko nawanggar
Block:
Page 23: (7) an me watko nawanggar
Page 23: saya topik disini tunggu
Page 23: ‘Untuk saya, saya menunggu di sini.’
Page 23: (8) an-a watko mu-a metko
Page 23: saya-fokus disini mereka-fokus disana
Page 23: ‘ Saya  ada di sini,  mereka  ada di sana.’
-----
New block starting at line no 372
Current line text: • prenuptial negotiations: narr2
Block:
New block starting at line no 663
Current line text: born level
Block:
New block starting at line no 691
Current line text: 1.5 Previous accounts of Kalamang and its genealogical affiliations
Block:
New block starting at line no 707
Current line text: affiliations
Block:
New block starting at line no 1045
Current line text: (1) bal se sor=at koraru
Block:
Page 52: (1) bal se sor=at koraru
Page 52: dog iam fish=obj bite
Page 52: ‘The dog has bitten the fish.’ [stim2_3:45]
Page 52: (2) mu kiem
Page 52: 3pl run
Page 52: ‘They run.’ [narr40_15:26]
Page 52: (3) ma reitkon purap-i an=at kamat=et
Page 52: 3sg hundred fifty-objqnt 1sg=obj send=irr
Page 52: ‘He sent me one hundred and fifty [thousand rupiah].’ [conv12_3:09]
-----
New block starting at line no 1086
Current line text: (4) mu pas sem=ten=at koup
Block:
Page 53: (4) mu pas sem=ten=at koup
Page 53: 3pl woman afraid-adj=obj hug
Page 53: ‘They hugged the scared woman.’ [elic_adj19_8]
-----
New block starting at line no 1187
Current line text: (5) an se toni min=kin
Block:
Page 56: (5) an se toni min=kin
Page 56: 1sg iam want sleep=vol
Page 56: ‘I already wanted to sleep.’ [narr32_0:18]
-----
New block starting at line no 1198
Current line text: (6) Ma toni: “Eh, sor wa me tamandi, pi parinet ye, pi parairet,
Block:
Page 57: (6) Ma toni: “Eh, sor wa me tamandi, pi parinet ye, pi parairet,
Page 57: ma toni eh sor wa me tamandi pi parin=et ye pi parair=et
Page 57: 3sg say hey fish prox top how 1pl.incl sell=irr or 1pl.incl split=irr
Page 57: siraet.”
Page 57: sira=et
Page 57: salt=irr
Page 57: ‘He said: “Hey, these fish, how [should we treat them]? Do we sell them,
Page 57: or do we split and salt them?”’ [narr8_5:34]
-----
New block starting at line no 1379
Current line text: (1) /pep/ ‘pig’ + /at/ ‘obj’ [ˈpewat̚] ‘pig.obj’
Block:
Page 62: (1) /pep/ ‘pig’ + /at/ ‘obj’ [ˈpewat̚] ‘pig.obj’
Page 62: /et/ ‘canoe’ + /at/ ‘obj’ [ˈerat̚] ‘canoe.obj’
Page 62: /tektek/ ‘knife’ + /at/ ‘obj’ [ˈtɛkteat̚] ‘knife.obj’
Page 62: (2) /saˈren/ ‘aground’ + /ten/ ‘at’ [wat saˈrɛndɛn] ‘old coconut’
Page 62: /kalaˈmaŋ/ ‘Karas’ + /ko/ ‘loc’ [kalaˈmaŋgo] ‘on Karas’
Page 62: /seram/ ‘Seram’ + /ka/ ‘lat’ [seramga] ‘from/to Seram’
Page 62: /leŋ/ ‘village’ + /ca/ ‘2sg.poss’ [ˈlɛŋɟa] ‘your village’
Page 62: (3) /ˈtan/ ‘arm; hand’ + /ko/ loc [ˈtaŋgo] ‘in hand; on arm’
Page 62: Kalamang has few affixes and many clitics. The latter can be divided into two
Page 62: groups: clitics of the first type show morphophonological integration with the
-----
New block starting at line no 1398
Current line text: (4) /ko/ ‘appl’ + /kaŋgirar/ ‘face’ [kokaŋgirar] ‘to face someone’
Block:
Page 63: (4) /ko/ ‘appl’ + /kaŋgirar/ ‘face’ [kokaŋgirar] ‘to face someone’
Page 63: Phonology and morphology are treated in Chapter 3, and morphological units
Page 63: and processes are described in Chapter 4.
-----
New block starting at line no 1406
Current line text: (5) ma ror cicaun=at pue
Block:
Page 63: (5) ma ror cicaun=at pue
Page 63: 3sg tree small=obj hit
Page 63: ‘He/she hits the small tree.’
-----
New block starting at line no 1415
Current line text: (6) ma=bon kiun=bon se bot
Block:
Page 63: (6) ma=bon kiun=bon se bot
Page 63: 3sg=com wife.3sg.poss=com iam go
Page 63: ‘He and his wife have gone.’
Page 63: (7) ka pasa=at sasul=ki na
Page 63: 2sg rice=obj spoon=ins consume
Page 63: ‘You eat rice with a spoon.’
Page 63: (8) canam kewe=at kiun=ki paruo
Page 63: man house=obj wife.3sg.poss=ben make
Page 63: ‘The man makes a house for his wife.’
-----
New block starting at line no 1426
Current line text: (9) ma per=kap
Block:
Page 64: (9) ma per=kap
Page 64: 3sg water=sim
Page 64: ‘It’s like water.’
Page 64: (10) kasamin-an kewe=ko
Page 64: bird-1sg.poss house=loc
Page 64: ‘My bird is in the house.’
Page 64: (11) tumun wilak=ka bot
Page 64: child sea=lat go
Page 64: ‘The child goes to the sea.’
-----
New block starting at line no 1443
Current line text: (12) bal muap-un
Block:
Page 64: (12) bal muap-un
Page 64: dog food-3poss
Page 64: ‘the dog’s food’
Page 64: (13) bal eir kanggeit
Page 64: dog two play
Page 64: ‘Two dogs play.’
Page 64: (14) bal anggon kanggeit
Page 64: dog 1sg.prox play
Page 64: ‘My dog plays.’
Page 64: (15) bal wa kanggeit
Page 64: dog prox play
Page 64: ‘This dog plays.’
Page 64: (16) bal kotur-ten kanggeit
Page 64: dog dirty-at play
Page 64: ‘A dirty dog plays.’
-----
New block starting at line no 1473
Current line text: (17) ki pi=at konawaruo
Block:
Page 65: (17) ki pi=at konawaruo
Page 65: 2pl 1pl.incl=obj forget
Page 65: ‘You forget us.’
Page 65: (18) ma-tain gonggin
Page 65: 3sg-alone know
Page 65: ‘Only she knows.’
Page 65: (19) Ramina ma-hutak bara
Page 65: Ramina 3sg-alone descend
Page 65: ‘Only Ramina comes down.’
Page 65: (20) in-naninggan bo kelek=ko
Page 65: 1pl.excl-all go mountain=loc
Page 65: ‘We all go to the mountain.’
Page 65: (21) mu muin=at jie
Page 65: 3pl 3pl.poss=obj get
Page 65: ‘They get theirs.’
-----
New block starting at line no 1493
Current line text: (22) Safril esun Juaria tara-un=at gerket
Block:
Page 65: (22) Safril esun Juaria tara-un=at gerket
Page 65: Safril father.3poss Juaria grandfather-3poss=obj ask
Page 65: ‘Safril’s father asks Juaria’s grandfather.’
-----
New block starting at line no 1529
Current line text: (23) tumtum per-an anggon na
Block:
Page 67: (23) tumtum per-an anggon na
Page 67: children water-1sg.poss 1sg.poss consume
Page 67: ‘Children drink my water.’
-----
New block starting at line no 1540
Current line text: (24) guru leng=kin
Block:
Page 67: (24) guru leng=kin
Page 67: teacher village=poss
Page 67: ‘the teacher of the village/the village teacher’
-----
New block starting at line no 1560
Current line text: form gloss pronominal adnominal identificational
Block:
Page 68: (25) wangga mei
Page 68: prox.lat come.imp
Page 68: ‘Come here!’
Page 68: (26) an don met mormor
Page 68: 1sg thing dist.obj hide
Page 68: ‘I hide that thing.’
Page 68: (27) mu amdir yawet paruot=kin
Page 68: 3pl garden down.obj make=vol
Page 68: ‘They want to make that garden down there.’
Page 68: (28) pulor opa tamatko
Page 68: betel_vine ana where
Page 68: ‘Where is that betel vine (that we just saw or talked about)?’
-----
New block starting at line no 1603
Current line text: (29) buok  ‘betel’ → buokbuok  ‘to chew betel’
Block:
Page 69: (29) buok  ‘betel’ → buokbuok  ‘to chew betel’
Page 69: (30) per-na, wat-na
Page 69: water-consume, coconut-consume
Page 69: ‘to drink water, to eat coconut’
-----
New block starting at line no 1612
Current line text: (31) kerkap  ‘to be red’ → kerkap∼kap  ‘to be very red’
Block:
Page 69: (31) kerkap  ‘to be red’ → kerkap∼kap  ‘to be very red’
Page 69: (32) paruo  ‘to do’ → paruo∼paruo  ‘to usually do; to do for a long time’
Page 69: (33) winyal  ‘to fish’ → winyal∼winyal  ‘to fish for a long time; to fish in different
Page 69: places in an area’
Page 69: The following four valency-changing operations and constructions are attested:
-----
New block starting at line no 1623
Current line text: (34) ma-tain se un-deir=i luk
Block:
Page 70: (34) ma-tain se un-deir=i luk
Page 70: 3sg-alone iam refl-bring=plnk come
Page 70: ‘She came herself.’ (Lit. ‘She brought herself coming.’) [narr24_5:33]
Page 70: (35) mu nau=tu
Page 70: 3pl recp=hit
Page 70: ‘They hit each other.’
Page 70: (36) mier torpes-ko=ar
Page 70: 3du shell-appl-dive
Page 70: ‘They two dive for shells.’
Page 70: (37) mu ror=at di=maruan
Page 70: 3pl wood=obj caus=move_seawards
Page 70: ‘They move the wood seawards.’
-----
New block starting at line no 1647
Current line text: (38) in kiem
Block:
Page 70: (38) in kiem
Page 70: 1pl.excl flee
Page 70: ‘We flee.’
Page 70: (39) in sor=at potma
Page 70: 1pl.excl fish=obj cut
Page 70: ‘We cut fish.’
-----
New block starting at line no 1664
Current line text: (40) mu tok watko
Block:
Page 71: (40) mu tok watko
Page 71: 3pl still there
Page 71: ‘They are still there.’
Page 71: (41) tumun kon guru
Page 71: child one teacher
Page 71: ‘One child is a teacher.’
Page 71: (42) kewe-an eir
Page 71: house-3poss two
Page 71: ‘I have two houses.’
-----
New block starting at line no 1683
Current line text: (43) ma ecien=i bara
Block:
Page 72: (43) ma ecien=i bara
Page 72: 3sg return=plnk descend
Page 72: ‘He returns down.’
-----
New block starting at line no 1692
Current line text: (44) ma ecien=i kewe=ko
Block:
Page 72: (44) ma ecien=i kewe=ko
Page 72: 3sg return=plnk house=loc
Page 72: ‘He returns home.’
Page 72: (45) ma sara bo karop-un osa-t=ko
Page 72: 3sg ascend go branch-3poss up-t=loc
Page 72: ‘He climbed up to the branch up there.’ [conv12_16:39]
-----
New block starting at line no 1702
Current line text: (46) ka mu ∅= te mu na
Block:
Page 72: (46) ka mu ∅= te mu na
Page 72: 2sg 3pl give=nfin 3pl consume
Page 72: ‘You give [the food] to them, they eat. [conv11_5:18]
-----
New block starting at line no 1720
Current line text: (47) an se tumun-an=at boubou
Block:
Page 73: (47) an se tumun-an=at boubou
Page 73: 1sg iam child-1sg.poss=obj bathe
Page 73: ‘I already bathed my child.’
Page 73: (48) an se tumun-an=at boubou=nin
Page 73: 1sg iam child-1sg.poss=obj bathe=neg
Page 73: ‘I’m not bathing my child anymore.’
Page 73: (49) an tok tumun-an=at boubou
Page 73: 1sg still child-1sg.poss=obj bathe
Page 73: ‘I’m still bathing my child.’
Page 73: (50) an tok tumun-an=at boubou=nin
Page 73: 1sg yet child-1sg.poss=obj bathe=neg
Page 73: ‘I haven’t yet bathed my child.’
-----
New block starting at line no 1736
Current line text: (51) canam me me ma kip=at sem
Block:
Page 73: (51) canam me me ma kip=at sem
Page 73: man dist top 3sg snake=obj afraid
Page 73: ‘As for that man, he is afraid of snakes.’
Page 73: (52) canam me me kip=at sem
Page 73: man dist top snake=obj afraid
Page 73: ‘That man is afraid of snakes.’
Page 73: (53) ka neba=at=a paruo
Page 73: 2sg what=obj=foc do
Page 73: ‘What are you doing?’
-----
New block starting at line no 1854
Current line text: (1) bilabials: /p – b – m – w/
Block:
Page 80: (1) bilabials: /p – b – m – w/
Page 80: pol  ‘sap’ [pol]
Page 80: bol  ‘mouth’ [bol]
Page 80: mul-  ‘side’ [mul]
Page 80: wol  ‘family’ [wol]
Page 80: (2) alveolars: /t – d – s – n – r – l/
Page 80: tan  ‘arm’ [tan]
Page 80: dan  ‘to bury’ [dan]
Page 80: sanam  ‘scabies’ [ˈsa.nam]
Page 80: na  ‘to consume’ [na]
Page 80: ra  ‘to hear’ [ra]
Page 80: lam  ‘soft coral’ [lam]
-----
New block starting at line no 1884
Current line text: meaningful.
Block:
New block starting at line no 1886
Current line text: independent units fill slots in the clause, these may be shuffled around for
Block:
New block starting at line no 1972
Current line text: (1) in pep-mang- un = at paruon
Block:
Page 139: (1) in pep-mang- un = at paruon
Page 139: 1pl.excl pig-language-3poss=obj make
Page 139: ‘We’re making pig’s language [= ugly language].’ [conv1_7:15]
-----
New block starting at line no 1989
Current line text: (2) A:  naman=a se bot
Block:
Page 139: (2) A:  naman=a se bot
Page 139: who=foc iam go
Page 139: ‘Who has already gone?’
Page 139: B:  *an se
Page 139: 1sg iam
Page 139: ‘Me.’ [elic]
-----
New block starting at line no 1998
Current line text: (3) mat dan=i koyet se ecien=i sara
Block:
Page 139: (3) mat dan=i koyet se ecien=i sara
Page 139: 3sg.obj bury=plnk finish iam return=plnk ascend
Page 139: ‘After burying him [we] went back up.’ [narr2_0:34]
-----
New block starting at line no 2006
Current line text: (4) Emun se... se wanir.
Block:
Page 140: (4) Emun se... se wanir.
Page 140: emun se se wanir
Page 140: mother.3poss iam iam twice
Page 140: ‘Her mother [did it] already... already twice.’ [narr25_1:45]
-----
New block starting at line no 2011
Current line text: (5) A:  ka se bot
Block:
Page 140: (5) A:  ka se bot
Page 140: 2sg iam go
Page 140: ‘Have you gone already?’
Page 140: B:  *se
Page 140: iam
Page 140: ‘Yes/already.’
-----
New block starting at line no 2024
Current line text: (6) A:  ki se kai=at rep
Block:
Page 140: (6) A:  ki se kai=at rep
Page 140: 2pl iam firewood=obj get
Page 140: ‘Did you already get firewood?’
Page 140: B:  tok
Page 140: not.yet
Page 140: ‘Not yet.’ [conv9_31:24]
-----
New block starting at line no 2179
Current line text: (7) a. /ˌmisilˈmisil/ ‘cement floor’
Block:
Page 145: (7) a. /ˌmisilˈmisil/ ‘cement floor’
Page 145: b. /ˈwuorˌwuor/ ‘to dream’
Page 145: c. /nokˈnok/ ‘to whisper’ (cf. /noˈkidak/ ‘to be silent’)
Page 145: d. /boukˈbouk/ ‘to bark’
Page 145: e. /korˈtaptap/ ‘to cut out’
Page 145: f. /ˈmarmar/ ‘to walk’
Page 145: g. /ˌsiŋa(t)ˈsiŋat/ ‘ant’
Page 145: h. /paŋˈgawaŋˌga/ ‘leech’
-----
New block starting at line no 2246
Current line text: (8) an se koi yal yal yal tebol-suban war=i war=i
Block:
Page 147: (8) an se koi yal yal yal tebol-suban war=i war=i
Page 147: 1sg iam again paddle paddle paddle reef_edge-fish fish=plnk fish=plnk
Page 147: eh sor nat=nin
Page 147: int.e fish consume=neg
Page 147: ‘I paddled and paddled again, fished at the reef edge, fished and fished,
Page 147: the fish didn’t bite.’ [narr8_1:02]
-----
New block starting at line no 2254
Current line text: (9) warkin naman=et pi wandi siktak∼tak=i tiri∼tiri
Block:
Page 147: (9) warkin naman=et pi wandi siktak∼tak=i tiri∼tiri
Page 147: tide deep=irr 1pl.excl like_this slow∼ints=plnk sail∼prog
Page 147: tiri∼tiri
Page 147: sail∼prog
Page 147: ‘When the tide is deep we sail slowly like this.’ [conv1_1:33]
-----
New block starting at line no 2264
Current line text: (10) ma-mun ma neba ewa∼wa∼ewawa =in [ ... ]  ewa∼wa∼ewawa
Block:
Page 148: (10) ma-mun ma neba ewa∼wa∼ewawa =in [ ... ]  ewa∼wa∼ewawa
Page 148: 3sg-proh 3sg ph talk∼prog∼prog=proh talk∼prog∼prog
Page 148: ‘She shouldn’t talk, talk [disturbing].’ [conv10_15:23]
-----
New block starting at line no 2280
Current line text: (11) yap_seran-un
Block:
Page 148: (11) yap_seran-un
Page 148: yam-3poss
Page 148: ‘their yam’ [conv10_16:03]
Page 148: (12) min-kalot=at kasi bersi
Page 148: sleep-room=obj give clean
Page 148: ‘clean the bedroom’ [narr41_0:13]
-----
New block starting at line no 2308
Current line text: (13) a.  an ˈperat ˈna
Block:
Page 149: (13) a.  an ˈperat ˈna
Page 149: an per=at na
Page 149: 1sg water=obj consume
Page 149: ‘I drink water.’
Page 149: b.  an ˈperna
Page 149: an per-na
Page 149: 1sg water-consume
Page 149: ‘I drink water.’ [elic_inc_2]
-----
New block starting at line no 2322
Current line text: (14) Juaria se muawaruoni koyet.
Block:
Page 149: (14) Juaria se muawaruoni koyet.
Page 149: Juaria se muap-paruon=i koyet
Page 149: Juaria iam food-make=plnk finish
Page 149: ‘Juaria has cooked.’ [narr7_12:08]
Page 149: (15) Mama Tua kureraparuo.
Page 149: Mama Tua kurera-paruo
Page 149: Mama Tua basket-make
Page 149: ‘Mama Tua making a basket.’ [stim42_4:26]
-----
New block starting at line no 2349
Current line text: (16) dudan-mur-un
Block:
Page 150: (16) dudan-mur-un
Page 150: sibling-kin.pl-3poss
Page 150: ‘his/her siblings’
-----
New block starting at line no 2360
Current line text: (17) ma sontum leng-et=at merengguen
Block:
Page 150: (17) ma sontum leng-et=at merengguen
Page 150: 3sg person village-nmlz=obj gather
Page 150: ‘He gathered the village people.’ [narr27_3:17]
Page 150: (18) don wa me se amkeit-et=kongga
Page 150: thing prox top iam give_birth-nmlz=an.lat
Page 150: ‘This thing comes from the birth parent.’ [conv20_38:53]
-----
New block starting at line no 2374
Current line text: (19) an kewe= at=a kon-i paruo
Block:
Page 151: (19) an kewe= at=a kon-i paruo
Page 151: 1sg house=obj=foc one-objqnt make
Page 151: ‘I made a house.’ [narr41_0:45]
Page 151: (20) ka me or= ko=te
Page 151: 2sg top back=loc=imp
Page 151: ‘You’re in the back!’ [narr19_5:00]
-----
New block starting at line no 2427
Current line text: root deir jie
Block:
New block starting at line no 2441
Current line text: (1) mu toni kalis=kin
Block:
Page 154: (1) mu toni kalis=kin
Page 154: 3pl think rain=vol
Page 154: ‘They think it will rain.’ [narr22_4:04]
-----
New block starting at line no 2446
Current line text: (2) teun ten
Block:
Page 155: (2) teun ten
Page 155: fruit bad
Page 155: ‘The fruits are bad.’ [narr13_4:14]
Page 155: (3) mu kiem
Page 155: 3pl run
Page 155: ‘They run.’ [narr40_15:26]
Page 155: (4) emun tumun=at narorar
Page 155: mother child=obj take_by_hand
Page 155: ‘The mother takes the child by the hand.’ [stim4_4:47]
Page 155: (5) mu kawir-un=at mat naunak
Page 155: 3pl hat-3poss=obj 3sg.obj show
Page 155: ‘They showed him the hat.’ [stim31_2:30]
-----
New block starting at line no 2461
Current line text: (6) in se tiri yecie
Block:
Page 155: (6) in se tiri yecie
Page 155: 1pl.excl iam sail return
Page 155: ‘We sailed back.’ [narr44_2:56]
Page 155: (7) ma kahen=i baran
Page 155: 3sg far=plnk descend
Page 155: ‘He goes down far.’ [stim44_0:32]
-----
New block starting at line no 2474
Current line text: (8) a.  ror-potma
Block:
Page 155: (8) a.  ror-potma
Page 155: wood-cut
Page 155: ‘to cut wood’ [narr7_4:13]
Page 155: b.  ror paramuan= ten
Page 155: wood cut=at
Page 155: ‘cut wood (wood that is cut)’ [elic_vvsa_4]
-----
New block starting at line no 2484
Current line text: (9) a.  tumun ririn = ten kiem
Block:
Page 156: (9) a.  tumun ririn = ten kiem
Page 156: child tall=at run
Page 156: ‘The tall child runs.’
Page 156: b.  tumun kiem = ten ririn
Page 156: child run=at tall
Page 156: ‘The running child is tall.’ [elic_adj_45]
-----
New block starting at line no 2493
Current line text: (10) a.  don mun = ten wandi=et ka bisa na=ta
Block:
Page 156: (10) a.  don mun = ten wandi=et ka bisa na=ta
Page 156: thing rotten=at like_this=irr 2sg can eat=nfin
Page 156: ‘You can eat rotten things like this.’ [narr39_7:35]
Page 156: b.  tumun tur = ten ma elao melalu
Page 156: child fall=at 3sg down.loc sit
Page 156: ‘The fallen child (he) sits on the floor.’ [elic_vvsa_12]
Page 156: c.  tumun tiri = ten ladan kerkap=ten=at sabur
Page 156: child run=at shirt red=at=obj wear
Page 156: ‘The running child wears a red shirt.’ [elic_vvsa_13]
Page 156: d.  tumun doa=at nabaca = ten ladan kerkap=ten=at sabur
Page 156: child prayer=obj read=at shirt red=at=obj wear
Page 156: ‘The child that is reading a prayer wears a red shirt.’ [elic_vvsa_15]
-----
New block starting at line no 2510
Current line text: (11) mu fiber temun kerunggo
Block:
Page 156: (11) mu fiber temun kerunggo
Page 156: 3pl fibre_boat big inside
Page 156: ‘They are in a big fibre boat.’ [conv14_10:45]
-----
New block starting at line no 2520
Current line text: (12) a. [ tumun tabusik wa ] NP
Block:
Page 157: (12) a. [ tumun tabusik wa ] NP
Page 157: child short prox
Page 157: ‘this short child’
Page 157: b. [ tumun wa ] NP [ tabusik ] Pred
Page 157: child prox short

In [38]:
final_blocks[0]

[{'page_num': 21,
  'line_no': 76,
  'text': '(1) I drùva schòn in téc da saprèndar anzjaman',
  'line': {'text': '(1) I drùva schòn in téc da saprèndar anzjaman',
   'spans': [{'text': '(1)',
     'x0': 64.20800018310547,
     'y0': 387.9992370605469,
     'x1': 74.63710021972656,
     'y1': 400.43560791015625,
     'font': 'LibertinusSerif-Regular',
     'size': 10.909099578857422,
     'block': {'number': 8,
      'type': 0,
      'bbox': (64.20800018310547,
       387.9992370605469,
       407.21246337890625,
       471.6976318359375),
      'lines': [{'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': '(1)',
          'origin': (64.20800018310547, 397.7519836425781),
          'bbox': (64.20800018310547,
           387.9992370605469,
           74.63710021972656,
           400.43560791015625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (64.20800018310547,
         387.9992370605469,
         74.63710021972656,
         400.43560791015625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'I',
          'origin': (85.5469970703125, 397.7519836425781),
          'bbox': (85.5469970703125,
           387.9992370605469,
           88.60154724121094,
           400.43560791015625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (85.5469970703125,
         387.9992370605469,
         88.60154724121094,
         400.43560791015625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'expl',
          'origin': (85.5469970703125, 411.3009948730469),
          'bbox': (85.5469970703125,
           401.5482482910156,
           106.28519439697266,
           413.984619140625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (85.5469970703125,
         401.5482482910156,
         106.28519439697266,
         413.984619140625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'drùva',
          'origin': (109.01200103759766, 397.7519836425781),
          'bbox': (109.01200103759766,
           387.9992370605469,
           134.3756561279297,
           400.43560791015625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (109.01200103759766,
         387.9992370605469,
         134.3756561279297,
         400.43560791015625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'need.prs.3sg',
          'origin': (109.01200103759766, 411.3009948730469),
          'bbox': (109.01200103759766,
           401.5482482910156,
           165.71731567382812,
           413.984619140625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (109.01200103759766,
         401.5482482910156,
         165.71731567382812,
         413.984619140625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'schòn',
          'origin': (168.44500732421875, 397.7519836425781),
          'bbox': (168.44500732421875,
           387.9992370605469,
           192.7286376953125,
           400.43560791015625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (168.44500732421875,
         387.9992370605469,
         192.7286376953125,
         400.43560791015625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'indeed',
          'origin': (168.44500732421875, 411.3009948730469),
          'bbox': (168.44500732421875,
           401.5482482910156,
           198.2486572265625,
           413.984619140625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (168.44500732421875,
         401.5482482910156,
         198.2486572265625,
         413.984619140625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'in',
          'origin': (200.98699951171875, 397.7519836425781),
          'bbox': (200.98699951171875,
           387.9992370605469,
           209.64881896972656,
           400.43560791015625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (200.98699951171875,
         387.9992370605469,
         209.64881896972656,
         400.43560791015625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'indef.m.sg',
          'origin': (200.98699951171875, 411.3009948730469),
          'bbox': (200.98699951171875,
           401.5482482910156,
           249.78341674804688,
           413.984619140625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (200.98699951171875,
         401.5482482910156,
         249.78341674804688,
         413.984619140625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'téc',
          'origin': (252.50999450683594, 397.7519836425781),
          'bbox': (252.50999450683594,
           387.9992370605469,
           264.55364990234375,
           400.43560791015625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (252.50999450683594,
         387.9992370605469,
         264.55364990234375,
         400.43560791015625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'bit',
          'origin': (252.50999450683594, 411.3009948730469),
          'bbox': (252.50999450683594,
           401.5482482910156,
           264.29180908203125,
           413.984619140625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (252.50999450683594,
         401.5482482910156,
         264.29180908203125,
         413.984619140625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'da',
          'origin': (267.281005859375, 397.7519836425781),
          'bbox': (267.281005859375,
           387.9992370605469,
           277.9173583984375,
           400.43560791015625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (267.281005859375,
         387.9992370605469,
         277.9173583984375,
         400.43560791015625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'attr',
          'origin': (267.281005859375, 411.3009948730469),
          'bbox': (267.281005859375,
           401.5482482910156,
           289.9283142089844,
           413.984619140625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (267.281005859375,
         401.5482482910156,
         289.9283142089844,
         413.984619140625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'saprèndar',
          'origin': (292.6449890136719, 397.7519836425781),
          'bbox': (292.6449890136719,
           387.9992370605469,
           335.58319091796875,
           400.43560791015625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (292.6449890136719,
         387.9992370605469,
         335.58319091796875,
         400.43560791015625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'refl.take.inf',
          'origin': (292.6449890136719, 411.3009948730469),
          'bbox': (292.6449890136719,
           401.5482482910156,
           351.66339111328125,
           413.984619140625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (292.6449890136719,
         401.5482482910156,
         351.66339111328125,
         413.984619140625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'anzjaman',
          'origin': (354.3900146484375, 397.7519836425781),
          'bbox': (354.3900146484375,
           387.9992370605469,
           397.7209777832031,
           400.43560791015625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (354.3900146484375,
         387.9992370605469,
         397.7209777832031,
         400.43560791015625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'together',
          'origin': (354.3900146484375, 411.3009948730469),
          'bbox': (354.3900146484375,
           401.5482482910156,
           391.9173583984375,
           413.984619140625)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (354.3900146484375,
         401.5482482910156,
         391.9173583984375,
         413.984619140625)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'da',
          'origin': (85.54702758789062, 425.84600830078125),
          'bbox': (85.54702758789062,
           416.09326171875,
           96.18339538574219,
           428.5296325683594)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (85.54702758789062,
         416.09326171875,
         96.18339538574219,
         428.5296325683594)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'comp',
          'origin': (85.54702758789062, 439.39599609375),
          'bbox': (85.54702758789062,
           429.64324951171875,
           109.3615951538086,
           442.0796203613281)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (85.54702758789062,
         429.64324951171875,
         109.3615951538086,
         442.0796203613281)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'raṣdá',
          'origin': (112.08802795410156, 425.84600830078125),
          'bbox': (112.08802795410156,
           416.09326171875,
           135.7716827392578,
           428.5296325683594)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (112.08802795410156,
         416.09326171875,
         135.7716827392578,
         428.5296325683594)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'talk.inf',
          'origin': (112.08802795410156, 439.39599609375),
          'bbox': (112.08802795410156,
           429.64324951171875,
           146.34341430664062,
           442.0796203613281)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (112.08802795410156,
         429.64324951171875,
         146.34341430664062,
         442.0796203613281)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'da',
          'origin': (149.07003784179688, 425.84600830078125),
          'bbox': (149.07003784179688,
           416.09326171875,
           159.70639038085938,
           428.5296325683594)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (149.07003784179688,
         416.09326171875,
         159.70639038085938,
         428.5296325683594)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'of',
          'origin': (149.07003784179688, 439.39599609375),
          'bbox': (149.07003784179688,
           429.64324951171875,
           157.9500274658203,
           442.0796203613281)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (149.07003784179688,
         429.64324951171875,
         157.9500274658203,
         442.0796203613281)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'Tujétsch',
          'origin': (162.43402099609375, 425.84600830078125),
          'bbox': (162.43402099609375,
           416.09326171875,
           197.93223571777344,
           428.5296325683594)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (162.43402099609375,
         416.09326171875,
         197.93223571777344,
         428.5296325683594)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'pn',
          'origin': (162.43402099609375, 439.39599609375),
          'bbox': (162.43402099609375,
           429.64324951171875,
           174.03041076660156,
           442.0796203613281)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (162.43402099609375,
         429.64324951171875,
         174.03041076660156,
         442.0796203613281)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'cun',
          'origin': (200.65902709960938, 425.84600830078125),
          'bbox': (200.65902709960938,
           416.09326171875,
           216.23721313476562,
           428.5296325683594)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (200.65902709960938,
         416.09326171875,
         216.23721313476562,
         428.5296325683594)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'with',
          'origin': (200.65902709960938, 439.39599609375),
          'bbox': (200.65902709960938,
           429.64324951171875,
           221.0808563232422,
           442.0796203613281)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (200.65902709960938,
         429.64324951171875,
         221.0808563232422,
         442.0796203613281)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'autars.',
          'origin': (223.8080291748047, 425.84600830078125),
          'bbox': (223.8080291748047,
           416.09326171875,
           253.57894897460938,
           428.5296325683594)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (223.8080291748047,
         416.09326171875,
         253.57894897460938,
         428.5296325683594)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,

In [89]:
base_prompt_fine_segmentation = f"""
You are an expert linguist who analyzes text from descriptive grammars. 
Your task is to identify linguistic examples within a block of text and 
label their internal structure. You must be precise and must not hallucinate 
missing information. Only use what is provided.

You will receive the text as a sequence of numbered lines in the format:

[1] text of line 1
[2] text of line 2
...

DEFINITIONS:
A linguistic example begins with a line that starts with a parenthesized
example label such as (2), (15), (3a), (4b), etc.
All lines following this belong to the example until the next example label
line or the end of the block.

Inside each example, lines fall into four categories:
- SOURCE: The original language sentence, here tuatschin Romansh.
- GLOSS: A word-by-word gloss containing morphological markers (e.g., "-", "=", gloss abbreviations).
- TRANSLATION: A free translation line, generally inside single quotes.
- COMMENT: Any additional text that does not fit the above categories. Eg: Heading, normal text, table content. 

YOUR TASKS:
1. Identify each example in the block.
2. For each example, provide:
   - "example_label": the parenthesized label such as "(2)" or "(3a). (none) if no label is present".
   - "start_line": the line number where the example begins.
   - "end_line": the line number where the example ends.
3. For each line inside the example boundaries, assign a "role":
   one of "SOURCE", "GLOSS", "TRANSLATION", or "COMMENT".
4. If an example appears incomplete (missing gloss or translation), 
   include `"status": "incomplete"`. Otherwise mark `"status": "complete"`.
5. Return ONLY valid JSON. No explanations. No prose.

Below is the block of numbered lines you must analyze:

{{block_text}}

Return the final JSON only.
"""

In [90]:
print(len(final_blocks))

702

In [91]:

with open("openai_api_key.txt", "r") as f:
    openai_api_key = f.read().strip()

from openai import OpenAI
client = OpenAI(api_key=openai_api_key)

In [92]:
responses = []

for block in tqdm(final_blocks):
    block_text = ""
    for idx, line in enumerate(block):
        block_text += f"[{idx+1}] {line['text']}\n"
    
    #print(block_text)
    prompt = base_prompt_fine_segmentation.format(block_text=block_text)
    #print(prompt)
    response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=[
            {"role": "system", "content": ""},
            {"role": "user", "content": prompt}
        ],
        temperature=0.2,
        max_tokens=1500,
    )
    responses.append(response)
    #print("-----")

100%|██████████| 702/702 [36:51<00:00,  3.15s/it]

In [93]:
cleaned_responses = []

for response in responses:
    text = response.choices[0].message.content
    # Parse JSON
    # Remove ```json and ``` if present
    text = re.sub(r"^```json", "", text.strip())
    text = re.sub(r"```$", "", text.strip())
    data = json.loads(text)
    print(len(data))
    #print(data)
    cleaned_responses.append(data)

1
1
3
1
2
3
1
1
1
3
1
1
3
3
5
5
1
1
1
4
2
3
4
2
3
1
2
1
4
3
2
1
1
1
1
1
1
1
1
1
1
2
2
2
1
2
2
1
4
2
2
2
4
1
3
2
4
2
1
2
1
1
1
1
4
1
1
1
1
1
1
2
4
2
1
1
2
2
1
1
1
1
1
1
1
1
2
1
5
2
1
1
1
2
1
1
1
2
4
1
2
1
2
2
1
1
1
1
1
3
3
2
1
2
1
1
1
1
2
2
1
2
1
1
1
1
0
3
2
1
2
4
1
5
1
2
1
2
1
1
2
1
2
1
2
1
2
1
1
4
1
2
1
1
3
2
1
1
2
1
1
2
1
2
2
2
2
1
3
2
3
1
1
1
1
1
3
2
1
2
2
2
1
0
2
1
1
1
1
1
1
1
1
0
2
1
1
1
1
1
1
1
2
3
3
1
1
1
2
2
2
2
1
2
4
1
2
1
2
2
1
1
2
1
3
1
2
2
1
2
2
1
1
4
2
2
2
1
1
2
4
2
2
1
1
1
1
2
1
1
1
1
1
3
1
1
2
1
1
3
3
1
1
1
0
2
2
3
1
1
2
2
1
1
2
1
1
1
1
3
2
0
2
2
1
2
1
1
2
1
0
1
2
1
1
1
1
2
1
1
1
1
2
2
3
3
1
2
1
1
2
3
4
5
1
2
5
3
1
1
1
1
3
2
1
2
2
2
2
1
1
2
2
1
2
1
3
1
2
1
2
1
1
1
3
3
1
3
3
2
1
2
2
1
3
2
1
1
1
2
1
1
1
2
2
1
1
2
2
1
2
3
2
1
2
4
1
1
2
1
1
1
1
1
2
1
2
1
1
1
1
1
1
2
3
1
1
1
1
1
2
1
2
1
1
2
2
1
1
2
1
1
1
1
1
5
2
2
1
1
2
2
3
1
1
2
2
1
1
3
2
1
1
1
4
1
1
2
2
1
4
1
1
2
2
1
1
2
1
1
3
1
1
2
1
1
1
1
2
2
2
4
1
1
2
1
1
3
1
3
3
1
1
1
1
1
2
8
1
1
1
2
6
3
2
2
1
1
4
1
1
1
1
5
0
1
1
2
4
1
3
1
1
1
1
3
2
3
2
1
2
2
1
1
1
1
1
0
3
2
1
1
1
2
2
2
2
1
1
1
1
1
1
1
2
2
0
1
2
1
1
1
1
1
1
2
3
1
3
1
1
2
1
1
2
2
1
1
2
1
2
1
2
4
2
2
2
3
1
1
2
1
1
3
2
3
1
2
1
1
1
1
2
1
1
1
1
1
1
2
1
2
2
1
2
3
1
1
2
1
1
0
5
1
2
2
3
3
1
1
2
1
3
3
2
2
1
1
2
2
1
1
1
1
1
1
1
1
1
2
1
1
3
1
3
4
2
4
2
1
1
1
2
1
4
2
1
3
1
1
1
1
2
2
1
1
2
1
1
1
4
3
2
1
3
6
2
1
1
1
1
3
6
1
3
2
1
1
2
4
2
1
1
2
1
2
2
1
1
6
4
5
1
3
3
1
3
3
8
8
8
7

In [94]:
# Save cleaned responses
with open("kalamang_cleaned_responses_parallel_new.json", "w", encoding="utf-8") as f:
    json.dump(cleaned_responses, f, indent=2, ensure_ascii=False)

In [34]:
with open("romansh_cleaned_responses_parallel.json", "r", encoding="utf-8") as f:
    cleaned_responses = json.load(f)

In [95]:
responses_flattened = []
for block in cleaned_responses:
    if "examples" in block:
        block = block["examples"]
    for example in block:
        if type(example) is str:
            print("Skipping invalid example:", example)
            print(block)
            continue
        for line in example["lines"]:
            #print(line)
            line_no = line['line_number'] if 'line_number' in line else 'N/A'
            if line_no == 'N/A':
                line_no = line['line'] if 'line' in line else None
                
            print(f"{line_no}: {line['role']}")
            if line["role"] == "TRANSLATION_COMMENT":
                line["role"] = "TRANSLATION"
            responses_flattened.append({
                "example_label": example["example_label"],
                "line_number": line_no,
                "role": line["role"],
            })

1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: SOURCE
5: GLOSS
6: GLOSS
7: TRANSLATION
8: COMMENT
1: SOURCE
2: SOURCE
3: SOURCE
4: SOURCE
5: SOURCE
6: SOURCE
7: SOURCE
8: SOURCE
1: COMMENT
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
13: SOURCE
14: GLOSS
15: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
13: SOURCE
14: GLOSS
15: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
1: SOURCE
2: SOURCE
3: GLOSS
4: TRANSLATION
1: SOURCE
2: SOURCE
3: SOURCE
4: SOURCE
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: COMMENT
2: COMMENT
3: COMMENT
4: COMMENT
5: COMMENT
6: COMMENT
7: COMMENT
8: COMMENT
9: COMMENT
10: COMMENT
11: COMMENT
12: COMMENT
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: SOURCE
3: SOURCE
4: SOURCE
5: SOURCE
6: SOURCE
7: SOURCE
8: SOURCE
1: SOURCE
2: GLOSS
3: SOURCE
4: GLOSS
5: TRANSLATION
6: COMMENT
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: TRANSLATION
5: SOURCE
6: GLOSS
7: GLOSS
8: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: TRANSLATION
5: SOURCE
6: GLOSS
7: GLOSS
8: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
13: SOURCE
14: GLOSS
15: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: COMMENT
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: COMMENT
8: SOURCE
9: GLOSS
10: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
3: SOURCE
4: GLOSS
5: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: GLOSS
7: GLOSS
8: TRANSLATION
9: COMMENT
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: SOURCE
5: GLOSS
6: GLOSS
7: TRANSLATION
8: COMMENT
9: SOURCE
10: GLOSS
11: TRANSLATION
1: COMMENT
2: COMMENT
3: COMMENT
4: COMMENT
5: COMMENT
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
13: SOURCE
14: GLOSS
15: TRANSLATION
16: SOURCE
17: GLOSS
18: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: COMMENT
2: COMMENT
3: COMMENT
4: COMMENT
5: COMMENT
6: COMMENT
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
6: SOURCE
7: GLOSS
8: COMMENT
9: COMMENT
1: SOURCE
2: TRANSLATION
3: SOURCE
4: TRANSLATION
5: SOURCE
6: TRANSLATION
7: SOURCE
8: TRANSLATION
1: SOURCE
2: SOURCE
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: COMMENT
2: SOURCE
3: GLOSS
4: TRANSLATION
5: SOURCE
6: GLOSS
7: TRANSLATION
8: SOURCE
9: GLOSS
10: TRANSLATION
11: SOURCE
12: GLOSS
13: TRANSLATION
2: SOURCE
3: GLOSS
4: TRANSLATION
5: SOURCE
6: GLOSS
7: TRANSLATION
9: SOURCE
10: GLOSS
11: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: COMMENT
2: SOURCE
3: GLOSS
4: TRANSLATION
5: SOURCE
6: GLOSS
7: TRANSLATION
8: SOURCE
9: GLOSS
10: TRANSLATION
3: SOURCE
4: GLOSS
5: TRANSLATION
1: COMMENT
2: SOURCE
3: GLOSS
4: TRANSLATION
5: SOURCE
6: GLOSS
7: TRANSLATION
8: SOURCE
9: GLOSS
10: TRANSLATION
11: SOURCE
12: GLOSS
13: TRANSLATION
1: COMMENT
2: SOURCE
3: GLOSS
4: TRANSLATION
5: SOURCE
6: GLOSS
7: TRANSLATION
1: COMMENT
2: SOURCE
3: GLOSS
4: TRANSLATION
5: SOURCE
6: GLOSS
7: TRANSLATION
1: COMMENT
2: COMMENT
3: COMMENT
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
12: SOURCE
13: GLOSS
14: TRANSLATION
1: COMMENT
2: COMMENT
1: COMMENT
2: COMMENT
1: COMMENT
2: COMMENT
1: COMMENT
2: COMMENT
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: GLOSS
13: GLOSS
14: TRANSLATION
15: SOURCE
16: GLOSS
17: TRANSLATION
1: SOURCE
2: SOURCE
3: SOURCE
4: SOURCE
5: SOURCE
6: SOURCE
7: SOURCE
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: SOURCE
4: GLOSS
5: TRANSLATION
6: COMMENT
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: SOURCE
4: GLOSS
5: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: SOURCE
7: GLOSS
8: TRANSLATION
9: COMMENT
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: COMMENT
7: COMMENT
8: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: COMMENT
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: SOURCE
4: GLOSS
5: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: SOURCE
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: COMMENT
5: SOURCE
6: GLOSS
7: TRANSLATION
8: SOURCE
9: GLOSS
10: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: SOURCE
4: GLOSS
5: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: SOURCE
4: GLOSS
5: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: SOURCE
3: SOURCE
1: SOURCE
2: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: TRANSLATION
5: SOURCE
6: GLOSS
7: GLOSS
8: TRANSLATION
9: SOURCE
10: GLOSS
11: GLOSS
12: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
6: SOURCE
7: GLOSS
8: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: SOURCE
7: GLOSS
8: TRANSLATION
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
6: SOURCE
7: GLOSS
8: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: SOURCE
4: GLOSS
5: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: TRANSLATION
5: SOURCE
6: GLOSS
7: GLOSS
8: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: SOURCE
5: GLOSS
6: GLOSS
7: TRANSLATION
8: COMMENT
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: COMMENT
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
6: SOURCE
7: GLOSS
8: SOURCE
9: GLOSS
10: SOURCE
11: GLOSS
12: TRANSLATION
13: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: GLOSS
7: GLOSS
8: TRANSLATION
9: COMMENT
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: SOURCE
3: SOURCE
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: GLOSS
7: GLOSS
8: TRANSLATION
9: COMMENT
1: SOURCE
2: GLOSS
3: GLOSS
4: SOURCE
5: GLOSS
6: GLOSS
7: TRANSLATION
8: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: SOURCE
4: GLOSS
5: SOURCE
6: GLOSS
7: TRANSLATION
8: COMMENT
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: SOURCE
4: GLOSS
5: TRANSLATION
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
6: COMMENT
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: TRANSLATION
5: SOURCE
6: GLOSS
7: GLOSS
8: COMMENT
9: COMMENT
10: COMMENT
11: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
6: SOURCE
7: GLOSS
8: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: SOURCE
5: GLOSS
6: GLOSS
7: TRANSLATION
8: TRANSLATION
9: SOURCE
10: GLOSS
11: GLOSS
12: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
6: SOURCE
7: GLOSS
8: TRANSLATION
9: SOURCE
10: GLOSS
11: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: SOURCE
4: GLOSS
5: TRANSLATION
6: COMMENT
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
4: SOURCE
5: GLOSS
6: TRANSLATION
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
1: SOURCE
2: SOURCE
3: SOURCE
4: COMMENT
5: SOURCE
6: SOURCE
1: SOURCE
2: SOURCE
1: SOURCE
2: SOURCE
4: SOURCE
5: SOURCE
6: SOURCE
1: SOURCE
2: GLOSS
3: SOURCE
4: GLOSS
5: TRANSLATION
6: COMMENT
7: SOURCE
8: GLOSS
9: TRANSLATION
10: SOURCE
11: GLOSS
12: TRANSLATION
13: SOURCE
14: GLOSS
15: TRANSLATION
16: SOURCE
17: GLOSS
18: TRANSLATION
1: SOURCE
2: GLOSS
3: GLOSS
4: GLOSS
5: TRANSLATION
6: COMMENT
7: SOURCE
8: GLOSS
9: GLOSS
10: GLOSS
11: TRANSLATION
12: COMMENT
13: SOURCE
14: GLOSS
15: GLOSS
16: GLOSS
17: TRANSLATION
1: SOURCE
2: GLOSS
3: TRANSLATION
1: SOURCE

In [96]:
# Draw the extracted examples on the pdf
print("Opening PDF file...")
doc = pymupdf.open(pdf_file_path)
print("PDF file opened successfully.")


temp_role = None
prev_line = -1
final_roles = []

prev_role = None


for block, resp in zip(final_blocks, cleaned_responses):
    if "examples" in resp:  
        resp = resp["examples"]
    for example in resp:
        start_line_idx = example["start_line"] - 1
        end_line_idx = example["end_line"] - 1
        for line_idx in range(start_line_idx, end_line_idx + 1):
            actual_role = None
            bline = block[line_idx]
            page_num = bline["page_num"]
            page = doc[page_num - 1]
            bbox = bline["bbox"]
            rect = pymupdf.Rect(bbox)
            role = example["lines"][line_idx - start_line_idx]["role"]
            if role == "SOURCE":
                color = (0, 0, 1)  # Blue
            elif role == "GLOSS":
                color = (0, 1, 0)  # Green
            elif role == "TRANSLATION":
                color = (1, 0, 0)  # Red
            else:
                color = (1, 1, 0)  # Yellow for COMMENT

            
            if role == "GLOSS":
                # Check if line has italics in one if it's fonts
                spans = bline["line"]["spans"]
                #print("Line:", bline["text"])
                #print([s["font"] for s in spans])
                has_italics = any("Italic" in s["font"] for s in spans) or any("Semibold" in s["font"] for s in spans)
                if has_italics:
                    color = (0, 0, 0)  # Black for GLOSS with italics
                    actual_role = "SOURCE"
                    
            
            elif temp_role is not None and role == "COMMENT" and line_idx == prev_line + 1:
                color = (1, 0.5, 0)  # Orange for COMMENT after other roles
                actual_role = "TRANSLATION"
                prev_line = line_idx

            # Check if the gloss

            else:
                temp_role = None
            if temp_role is None and role != "SOURCE" and role!="COMMENT":
                temp_role = role
                prev_line = line_idx

            
            final_roles.append({
                "page_num": page_num,
                "bline": bline,
                "role": actual_role if actual_role is not None else role,
                
            })
            print(f"Page {page_num}, Line: {bline['text']}, Role: {actual_role if actual_role is not None else role}")
            
            

            page.draw_rect(rect, color=color, width=0.5)
doc.save("output_with_fine_segmentation.pdf")

Opening PDF file...
PDF file opened successfully.
Page 20, Line: (1) hukat kon anggon yuwa, Role: SOURCE
Page 20, Line: jaring_ikan satu milik_saya ini, Role: GLOSS
Page 20, Line: ‘jaring ikan milik saya satu ini’, Role: TRANSLATION
Page 21, Line: (2) kaskas et-eir, Role: SOURCE
Page 21, Line: burung_camar hidup-dua, Role: GLOSS
Page 21, Line: ‘dua burung camar’, Role: TRANSLATION
Page 22, Line: (3) ma se guru, Role: SOURCE
Page 22, Line: dia sudah guru, Role: GLOSS
Page 22, Line: ‘Dia sudah (menjadi seorang) guru.’, Role: TRANSLATION
Page 22, Line: (4) ma me, Role: SOURCE
Page 22, Line: dia itu, Role: GLOSS
Page 22, Line: ‘Itu dia.’, Role: TRANSLATION
Page 22, Line: (5) im kansuor, Role: SOURCE
Page 22, Line: pisang empat, Role: GLOSS
Page 22, Line: ‘Ada empat pisang.’, Role: TRANSLATION
Page 22, Line: (6) ka-mun narabir-in, Role: SOURCE
Page 22, Line: kamu-jangan berteriak-jangan, Role: GLOSS
Page 22, Line: ‘Janganlah kamu berteriak!’, Role: TRANSLATION
Page 23, Line: (7) an me watko nawanggar, Role: SOURCE
Page 23, Line: saya topik disini tunggu, Role: GLOSS
Page 23, Line: ‘Untuk saya, saya menunggu di sini.’, Role: TRANSLATION
Page 23, Line: (8) an-a watko mu-a metko, Role: SOURCE
Page 23, Line: saya-fokus disini mereka-fokus disana, Role: GLOSS
Page 23, Line: ‘ Saya  ada di sini,  mereka  ada di sana.’, Role: TRANSLATION
Page 52, Line: (1) bal se sor=at koraru, Role: SOURCE
Page 52, Line: dog iam fish=obj bite, Role: GLOSS
Page 52, Line: ‘The dog has bitten the fish.’ [stim2_3:45], Role: TRANSLATION
Page 52, Line: (2) mu kiem, Role: SOURCE
Page 52, Line: 3pl run, Role: GLOSS
Page 52, Line: ‘They run.’ [narr40_15:26], Role: TRANSLATION
Page 52, Line: (3) ma reitkon purap-i an=at kamat=et, Role: SOURCE
Page 52, Line: 3sg hundred fifty-objqnt 1sg=obj send=irr, Role: GLOSS
Page 52, Line: ‘He sent me one hundred and fifty [thousand rupiah].’ [conv12_3:09], Role: TRANSLATION
Page 53, Line: (4) mu pas sem=ten=at koup, Role: SOURCE
Page 53, Line: 3pl woman afraid-adj=obj hug, Role: GLOSS
Page 53, Line: ‘They hugged the scared woman.’ [elic_adj19_8], Role: TRANSLATION
Page 56, Line: (5) an se toni min=kin, Role: SOURCE
Page 56, Line: 1sg iam want sleep=vol, Role: GLOSS
Page 56, Line: ‘I already wanted to sleep.’ [narr32_0:18], Role: TRANSLATION
Page 57, Line: (6) Ma toni: “Eh, sor wa me tamandi, pi parinet ye, pi parairet,, Role: SOURCE
Page 57, Line: ma toni eh sor wa me tamandi pi parin=et ye pi parair=et, Role: GLOSS
Page 57, Line: 3sg say hey fish prox top how 1pl.incl sell=irr or 1pl.incl split=irr, Role: GLOSS
Page 57, Line: siraet.”, Role: SOURCE
Page 57, Line: sira=et, Role: GLOSS
Page 57, Line: salt=irr, Role: GLOSS
Page 57, Line: ‘He said: “Hey, these fish, how [should we treat them]? Do we sell them,, Role: TRANSLATION
Page 57, Line: or do we split and salt them?”’ [narr8_5:34], Role: TRANSLATION
Page 62, Line: (1) /pep/ ‘pig’ + /at/ ‘obj’ [ˈpewat̚] ‘pig.obj’, Role: SOURCE
Page 62, Line: /et/ ‘canoe’ + /at/ ‘obj’ [ˈerat̚] ‘canoe.obj’, Role: SOURCE
Page 62, Line: /tektek/ ‘knife’ + /at/ ‘obj’ [ˈtɛkteat̚] ‘knife.obj’, Role: SOURCE
Page 62, Line: (2) /saˈren/ ‘aground’ + /ten/ ‘at’ [wat saˈrɛndɛn] ‘old coconut’, Role: SOURCE
Page 62, Line: /kalaˈmaŋ/ ‘Karas’ + /ko/ ‘loc’ [kalaˈmaŋgo] ‘on Karas’, Role: SOURCE
Page 62, Line: /seram/ ‘Seram’ + /ka/ ‘lat’ [seramga] ‘from/to Seram’, Role: SOURCE
Page 62, Line: /leŋ/ ‘village’ + /ca/ ‘2sg.poss’ [ˈlɛŋɟa] ‘your village’, Role: SOURCE
Page 62, Line: (3) /ˈtan/ ‘arm; hand’ + /ko/ loc [ˈtaŋgo] ‘in hand; on arm’, Role: SOURCE
Page 63, Line: (4) /ko/ ‘appl’ + /kaŋgirar/ ‘face’ [kokaŋgirar] ‘to face someone’, Role: COMMENT
Page 63, Line: (5) ma ror cicaun=at pue, Role: SOURCE
Page 63, Line: 3sg tree small=obj hit, Role: GLOSS
Page 63, Line: ‘He/she hits the small tree.’, Role: TRANSLATION
Page 63, Line: (6) ma=bon kiun=bon se bot, Role: SOURCE
Page 63, Line: 3sg=com wife.3sg.poss=com iam go, Role: GLOSS
Page 63, Line: ‘He and his wife have gone.’, Role: TRANSLATION
Page 63, Line: (7) ka pasa=at sasul=ki na, Role: SOURCE
Page 63, Line: 2sg rice=obj spoon=ins consume, Role: GLOSS
Page 63, Line: ‘You eat rice with a spoon.’, Role: TRANSLATION
Page 63, Line: (8) canam kewe=at kiun=ki paruo, Role: SOURCE
Page 63, Line: man house=obj wife.3sg.poss=ben make, Role: GLOSS
Page 63, Line: ‘The man makes a house for his wife.’, Role: TRANSLATION
Page 64, Line: (9) ma per=kap, Role: SOURCE
Page 64, Line: 3sg water=sim, Role: GLOSS
Page 64, Line: ‘It’s like water.’, Role: TRANSLATION
Page 64, Line: (10) kasamin-an kewe=ko, Role: SOURCE
Page 64, Line: bird-1sg.poss house=loc, Role: GLOSS
Page 64, Line: ‘My bird is in the house.’, Role: TRANSLATION
Page 64, Line: (11) tumun wilak=ka bot, Role: SOURCE
Page 64, Line: child sea=lat go, Role: GLOSS
Page 64, Line: ‘The child goes to the sea.’, Role: TRANSLATION
Page 64, Line: (12) bal muap-un, Role: SOURCE
Page 64, Line: dog food-3poss, Role: GLOSS
Page 64, Line: ‘the dog’s food’, Role: TRANSLATION
Page 64, Line: (13) bal eir kanggeit, Role: SOURCE
Page 64, Line: dog two play, Role: GLOSS
Page 64, Line: ‘Two dogs play.’, Role: TRANSLATION
Page 64, Line: (14) bal anggon kanggeit, Role: SOURCE
Page 64, Line: dog 1sg.prox play, Role: GLOSS
Page 64, Line: ‘My dog plays.’, Role: TRANSLATION
Page 64, Line: (15) bal wa kanggeit, Role: SOURCE
Page 64, Line: dog prox play, Role: GLOSS
Page 64, Line: ‘This dog plays.’, Role: TRANSLATION
Page 64, Line: (16) bal kotur-ten kanggeit, Role: SOURCE
Page 64, Line: dog dirty-at play, Role: GLOSS
Page 64, Line: ‘A dirty dog plays.’, Role: TRANSLATION
Page 65, Line: (17) ki pi=at konawaruo, Role: SOURCE
Page 65, Line: 2pl 1pl.incl=obj forget, Role: GLOSS
Page 65, Line: ‘You forget us.’, Role: TRANSLATION
Page 65, Line: (18) ma-tain gonggin, Role: SOURCE
Page 65, Line: 3sg-alone know, Role: GLOSS
Page 65, Line: ‘Only she knows.’, Role: TRANSLATION
Page 65, Line: (19) Ramina ma-hutak bara, Role: SOURCE
Page 65, Line: Ramina 3sg-alone descend, Role: GLOSS
Page 65, Line: ‘Only Ramina comes down.’, Role: TRANSLATION
Page 65, Line: (20) in-naninggan bo kelek=ko, Role: SOURCE
Page 65, Line: 1pl.excl-all go mountain=loc, Role: GLOSS
Page 65, Line: ‘We all go to the mountain.’, Role: TRANSLATION
Page 65, Line: (21) mu muin=at jie, Role: SOURCE
Page 65, Line: 3pl 3pl.poss=obj get, Role: GLOSS
Page 65, Line: ‘They get theirs.’, Role: TRANSLATION
Page 65, Line: (22) Safril esun Juaria tara-un=at gerket, Role: SOURCE
Page 65, Line: Safril father.3poss Juaria grandfather-3poss=obj ask, Role: GLOSS
Page 65, Line: ‘Safril’s father asks Juaria’s grandfather.’, Role: TRANSLATION
Page 67, Line: (23) tumtum per-an anggon na, Role: SOURCE
Page 67, Line: children water-1sg.poss 1sg.poss consume, Role: GLOSS
Page 67, Line: ‘Children drink my water.’, Role: TRANSLATION
Page 67, Line: (24) guru leng=kin, Role: SOURCE
Page 67, Line: teacher village=poss, Role: GLOSS
Page 67, Line: ‘the teacher of the village/the village teacher’, Role: TRANSLATION
Page 68, Line: (25) wangga mei, Role: SOURCE
Page 68, Line: prox.lat come.imp, Role: GLOSS
Page 68, Line: ‘Come here!’, Role: TRANSLATION
Page 68, Line: (26) an don met mormor, Role: SOURCE
Page 68, Line: 1sg thing dist.obj hide, Role: GLOSS
Page 68, Line: ‘I hide that thing.’, Role: TRANSLATION
Page 68, Line: (27) mu amdir yawet paruot=kin, Role: SOURCE
Page 68, Line: 3pl garden down.obj make=vol, Role: GLOSS
Page 68, Line: ‘They want to make that garden down there.’, Role: TRANSLATION
Page 68, Line: (28) pulor opa tamatko, Role: SOURCE
Page 68, Line: betel_vine ana where, Role: GLOSS
Page 68, Line: ‘Where is that betel vine (that we just saw or talked about)?’, Role: TRANSLATION
Page 69, Line: (29) buok  ‘betel’ → buokbuok  ‘to chew betel’, Role: SOURCE
Page 69, Line: (30) per-na, wat-na, Role: SOURCE
Page 69, Line: water-consume, coconut-consume, Role: GLOSS
Page 69, Line: ‘to drink water, to eat coconut’, Role: TRANSLATION
Page 69, Line: (31) kerkap  ‘to be red’ → kerkap∼kap  ‘to be very red’, Role: SOURCE
Page 69, Line: (32) paruo  ‘to do’ → paruo∼paruo  ‘to usually do; to do for a long time’, Role: SOURCE
Page 69, Line: (33) winyal  ‘to fish’ → winyal∼winyal  ‘to fish for a long time; to fish in different, Role: SOURCE
Page 69, Line: places in an area’, Role: SOURCE
Page 70, Line: (34) ma-tain se un-deir=i luk, Role: SOURCE
Page 70, Line: 3sg-alone iam refl-bring=plnk come, Role: GLOSS
Page 70, Line: ‘She came herself.’ (Lit. ‘She brought herself coming.’) [narr24_5:33], Role: TRANSLATION
Page 70, Line: (35) mu nau=tu, Role: SOURCE
Page 70, Line: 3pl recp=hit, Role: GLOSS
Page 70, Line: ‘They hit each other.’, Role: TRANSLATION
Page 70, Line: (36) mier torpes-ko=ar, Role: SOURCE
Page 70, Line: 3du shell-appl-dive, Role: GLOSS
Page 70, Line: ‘They two dive for shells.’, Role: TRANSLATION
Page 70, Line: (37) mu ror=at di=maruan, Role: SOURCE
Page 70, Line: 3pl wood=obj caus=move_seawards, Role: GLOSS
Page 70, Line: ‘They move the wood seawards.’, Role: TRANSLATION
Page 70, Line: (38) in kiem, Role: SOURCE
Page 70, Line: 1pl.excl flee, Role: GLOSS
Page 70, Line: ‘We flee.’, Role: TRANSLATION
Page 70, Line: (39) in sor=at potma, Role: SOURCE
Page 70, Line: 1pl.excl fish=obj cut, Role: GLOSS
Page 70, Line: ‘We cut fish.’, Role: TRANSLATION
Page 71, Line: (40) mu tok watko, Role: SOURCE
Page 71, Line: 3pl still there, Role: GLOSS
Page 71, Line: ‘They are still there.’, Role: TRANSLATION
Page 71, Line: (41) tumun kon guru, Role: SOURCE
Page 71, Line: child one teacher, Role: GLOSS
Page 71, Line: ‘One child is a teacher.’, Role: TRANSLATION
Page 71, Line: (42) kewe-an eir, Role: SOURCE
Page 71, Line: house-3poss two, Role: GLOSS
Page 71, Line: ‘I have two houses.’, Role: TRANSLATION
Page 72, Line: (43) ma ecien=i bara, Role: SOURCE
Page 72, Line: 3sg return=plnk descend, Role: GLOSS
Page 72, Line: ‘He returns down.’, Role: TRANSLATION
Page 72, Line: (44) ma ecien=i kewe=ko, Role: SOURCE
Page 72, Line: 3sg return=plnk house=loc, Role: GLOSS
Page 72, Line: ‘He returns home.’, Role: TRANSLATION
Page 72, Line: (45) ma sara bo karop-un osa-t=ko, Role: SOURCE
Page 72, Line: 3sg ascend go branch-3poss up-t=loc, Role: GLOSS
Page 72, Line: ‘He climbed up to the branch up there.’ [conv12_16:39], Role: TRANSLATION
Page 72, Line: (46) ka mu ∅= te mu na, Role: SOURCE
Page 72, Line: 2sg 3pl give=nfin 3pl consume, Role: GLOSS
Page 72, Line: ‘You give [the food] to them, they eat. [conv11_5:18], Role: TRANSLATION
Page 73, Line: (47) an se tumun-an=at boubou, Role: SOURCE
Page 73, Line: 1sg iam child-1sg.poss=obj bathe, Role: GLOSS
Page 73, Line: ‘I already bathed my child.’, Role: TRANSLATION
Page 73, Line: (48) an se tumun-an=at boubou=nin, Role: SOURCE
Page 73, Line: 1sg iam child-1sg.poss=obj bathe=neg, Role: GLOSS
Page 73, Line: ‘I’m not bathing my child anymore.’, Role: TRANSLATION
Page 73, Line: (49) an tok tumun-an=at boubou, Role: SOURCE
Page 73, Line: 1sg still child-1sg.poss=obj bathe, Role: GLOSS
Page 73, Line: ‘I’m still bathing my child.’, Role: TRANSLATION
Page 73, Line: (50) an tok tumun-an=at boubou=nin, Role: SOURCE
Page 73, Line: 1sg yet child-1sg.poss=obj bathe=neg, Role: GLOSS
Page 73, Line: ‘I haven’t yet bathed my child.’, Role: TRANSLATION
Page 73, Line: (51) canam me me ma kip=at sem, Role: SOURCE
Page 73, Line: man dist top 3sg snake=obj afraid, Role: GLOSS
Page 73, Line: ‘As for that man, he is afraid of snakes.’, Role: TRANSLATION
Page 73, Line: (52) canam me me kip=at sem, Role: SOURCE
Page 73, Line: man dist top snake=obj afraid, Role: GLOSS
Page 73, Line: ‘That man is afraid of snakes.’, Role: TRANSLATION
Page 73, Line: (53) ka neba=at=a paruo, Role: SOURCE
Page 73, Line: 2sg what=obj=foc do, Role: GLOSS
Page 73, Line: ‘What are you doing?’, Role: TRANSLATION
Page 80, Line: (1) bilabials: /p – b – m – w/, Role: COMMENT
Page 80, Line: pol  ‘sap’ [pol], Role: COMMENT
Page 80, Line: bol  ‘mouth’ [bol], Role: COMMENT
Page 80, Line: mul-  ‘side’ [mul], Role: COMMENT
Page 80, Line: wol  ‘family’ [wol], Role: COMMENT
Page 80, Line: (2) alveolars: /t – d – s – n – r – l/, Role: COMMENT
Page 80, Line: tan  ‘arm’ [tan], Role: COMMENT
Page 80, Line: dan  ‘to bury’ [dan], Role: COMMENT
Page 80, Line: sanam  ‘scabies’ [ˈsa.nam], Role: COMMENT
Page 80, Line: na  ‘to consume’ [na], Role: COMMENT
Page 80, Line: ra  ‘to hear’ [ra], Role: COMMENT
Page 80, Line: lam  ‘soft coral’ [lam], Role: COMMENT
Page 139, Line: (1) in pep-mang- un = at paruon, Role: SOURCE
Page 139, Line: 1pl.excl pig-language-3poss=obj make, Role: GLOSS
Page 139, Line: ‘We’re making pig’s language [= ugly language].’ [conv1_7:15], Role: TRANSLATION
Page 139, Line: (2) A:  naman=a se bot, Role: SOURCE
Page 139, Line: who=foc iam go, Role: GLOSS
Page 139, Line: ‘Who has already gone?’, Role: TRANSLATION
Page 139, Line: B:  *an se, Role: SOURCE
Page 139, Line: 1sg iam, Role: GLOSS
Page 139, Line: ‘Me.’ [elic], Role: TRANSLATION
Page 139, Line: (3) mat dan=i koyet se ecien=i sara, Role: SOURCE
Page 139, Line: 3sg.obj bury=plnk finish iam return=plnk ascend, Role: GLOSS
Page 139, Line: ‘After burying him [we] went back up.’ [narr2_0:34], Role: TRANSLATION
Page 140, Line: (4) Emun se... se wanir., Role: SOURCE
Page 140, Line: emun se se wanir, Role: GLOSS
Page 140, Line: mother.3poss iam iam twice, Role: GLOSS
Page 140, Line: ‘Her mother [did it] already... already twice.’ [narr25_1:45], Role: TRANSLATION
Page 140, Line: (5) A:  ka se bot, Role: SOURCE
Page 140, Line: 2sg iam go, Role: GLOSS
Page 140, Line: ‘Have you gone already?’, Role: TRANSLATION
Page 140, Line: B:  *se, Role: SOURCE
Page 140, Line: iam, Role: GLOSS
Page 140, Line: ‘Yes/already.’, Role: TRANSLATION
Page 140, Line: (6) A:  ki se kai=at rep, Role: SOURCE
Page 140, Line: 2pl iam firewood=obj get, Role: GLOSS
Page 140, Line: ‘Did you already get firewood?’, Role: TRANSLATION
Page 140, Line: B:  tok, Role: SOURCE
Page 140, Line: not.yet, Role: GLOSS
Page 140, Line: ‘Not yet.’ [conv9_31:24], Role: TRANSLATION
Page 145, Line: (7) a. /ˌmisilˈmisil/ ‘cement floor’, Role: SOURCE
Page 145, Line: b. /ˈwuorˌwuor/ ‘to dream’, Role: SOURCE
Page 145, Line: c. /nokˈnok/ ‘to whisper’ (cf. /noˈkidak/ ‘to be silent’), Role: SOURCE
Page 145, Line: d. /boukˈbouk/ ‘to bark’, Role: SOURCE
Page 145, Line: e. /korˈtaptap/ ‘to cut out’, Role: SOURCE
Page 145, Line: f. /ˈmarmar/ ‘to walk’, Role: SOURCE
Page 145, Line: g. /ˌsiŋa(t)ˈsiŋat/ ‘ant’, Role: SOURCE
Page 145, Line: h. /paŋˈgawaŋˌga/ ‘leech’, Role: SOURCE
Page 147, Line: (8) an se koi yal yal yal tebol-suban war=i war=i, Role: SOURCE
Page 147, Line: 1sg iam again paddle paddle paddle reef_edge-fish fish=plnk fish=plnk, Role: GLOSS
Page 147, Line: eh sor nat=nin, Role: SOURCE
Page 147, Line: int.e fish consume=neg, Role: GLOSS
Page 147, Line: ‘I paddled and paddled again, fished at the reef edge, fished and fished,, Role: TRANSLATION
Page 147, Line: the fish didn’t bite.’ [narr8_1:02], Role: TRANSLATION
Page 147, Line: (9) warkin naman=et pi wandi siktak∼tak=i tiri∼tiri, Role: SOURCE
Page 147, Line: tide deep=irr 1pl.excl like_this slow∼ints=plnk sail∼prog, Role: GLOSS
Page 147, Line: tiri∼tiri, Role: SOURCE
Page 147, Line: sail∼prog, Role: GLOSS
Page 147, Line: ‘When the tide is deep we sail slowly like this.’ [conv1_1:33], Role: TRANSLATION
Page 148, Line: (10) ma-mun ma neba ewa∼wa∼ewawa =in [ ... ]  ewa∼wa∼ewawa, Role: SOURCE
Page 148, Line: 3sg-proh 3sg ph talk∼prog∼prog=proh talk∼prog∼prog, Role: GLOSS
Page 148, Line: ‘She shouldn’t talk, talk [disturbing].’ [conv10_15:23], Role: TRANSLATION
Page 148, Line: (11) yap_seran-un, Role: SOURCE
Page 148, Line: yam-3poss, Role: GLOSS
Page 148, Line: ‘their yam’ [conv10_16:03], Role: TRANSLATION
Page 148, Line: (12) min-kalot=at kasi bersi, Role: SOURCE
Page 148, Line: sleep-room=obj give clean, Role: GLOSS
Page 148, Line: ‘clean the bedroom’ [narr41_0:13], Role: TRANSLATION
Page 149, Line: (13) a.  an ˈperat ˈna, Role: SOURCE
Page 149, Line: an per=at na, Role: GLOSS
Page 149, Line: 1sg water=obj consume, Role: GLOSS
Page 149, Line: ‘I drink water.’, Role: TRANSLATION
Page 149, Line: b.  an ˈperna, Role: SOURCE
Page 149, Line: an per-na, Role: GLOSS
Page 149, Line: 1sg water-consume, Role: GLOSS
Page 149, Line: ‘I drink water.’ [elic_inc_2], Role: TRANSLATION
Page 149, Line: (14) Juaria se muawaruoni koyet., Role: SOURCE
Page 149, Line: Juaria se muap-paruon=i koyet, Role: GLOSS
Page 149, Line: Juaria iam food-make=plnk finish, Role: GLOSS
Page 149, Line: ‘Juaria has cooked.’ [narr7_12:08], Role: TRANSLATION
Page 149, Line: (15) Mama Tua kureraparuo., Role: SOURCE
Page 149, Line: Mama Tua kurera-paruo, Role: GLOSS
Page 149, Line: Mama Tua basket-make, Role: GLOSS
Page 149, Line: ‘Mama Tua making a basket.’ [stim42_4:26], Role: TRANSLATION
Page 150, Line: (16) dudan-mur-un, Role: SOURCE
Page 150, Line: sibling-kin.pl-3poss, Role: GLOSS
Page 150, Line: ‘his/her siblings’, Role: TRANSLATION
Page 150, Line: (17) ma sontum leng-et=at merengguen, Role: SOURCE
Page 150, Line: 3sg person village-nmlz=obj gather, Role: GLOSS
Page 150, Line: ‘He gathered the village people.’ [narr27_3:17], Role: TRANSLATION
Page 150, Line: (18) don wa me se amkeit-et=kongga, Role: SOURCE
Page 150, Line: thing prox top iam give_birth-nmlz=an.lat, Role: GLOSS
Page 150, Line: ‘This thing comes from the birth parent.’ [conv20_38:53], Role: TRANSLATION
Page 151, Line: (19) an kewe= at=a kon-i paruo, Role: SOURCE
Page 151, Line: 1sg house=obj=foc one-objqnt make, Role: GLOSS
Page 151, Line: ‘I made a house.’ [narr41_0:45], Role: TRANSLATION
Page 151, Line: (20) ka me or= ko=te, Role: SOURCE
Page 151, Line: 2sg top back=loc=imp, Role: GLOSS
Page 151, Line: ‘You’re in the back!’ [narr19_5:00], Role: TRANSLATION
Page 154, Line: (1) mu toni kalis=kin, Role: SOURCE
Page 154, Line: 3pl think rain=vol, Role: GLOSS
Page 154, Line: ‘They think it will rain.’ [narr22_4:04], Role: TRANSLATION
Page 155, Line: (2) teun ten, Role: SOURCE
Page 155, Line: fruit bad, Role: GLOSS
Page 155, Line: ‘The fruits are bad.’ [narr13_4:14], Role: TRANSLATION
Page 155, Line: (3) mu kiem, Role: SOURCE
Page 155, Line: 3pl run, Role: GLOSS
Page 155, Line: ‘They run.’ [narr40_15:26], Role: TRANSLATION
Page 155, Line: (4) emun tumun=at narorar, Role: SOURCE
Page 155, Line: mother child=obj take_by_hand, Role: GLOSS
Page 155, Line: ‘The mother takes the child by the hand.’ [stim4_4:47], Role: TRANSLATION
Page 155, Line: (5) mu kawir-un=at mat naunak, Role: SOURCE
Page 155, Line: 3pl hat-3poss=obj 3sg.obj show, Role: GLOSS
Page 155, Line: ‘They showed him the hat.’ [stim31_2:30], Role: TRANSLATION
Page 155, Line: (6) in se tiri yecie, Role: SOURCE
Page 155, Line: 1pl.excl iam sail return, Role: GLOSS
Page 155, Line: ‘We sailed back.’ [narr44_2:56], Role: TRANSLATION
Page 155, Line: (7) ma kahen=i baran, Role: SOURCE
Page 155, Line: 3sg far=plnk descend, Role: GLOSS
Page 155, Line: ‘He goes down far.’ [stim44_0:32], Role: TRANSLATION
Page 155, Line: (8) a.  ror-potma, Role: SOURCE
Page 155, Line: wood-cut, Role: GLOSS
Page 155, Line: ‘to cut wood’ [narr7_4:13], Role: TRANSLATION
Page 155, Line: b.  ror paramuan= ten, Role: SOURCE
Page 155, Line: wood cut=at, Role: GLOSS
Page 155, Line: ‘cut wood (wood that is cut)’ [elic_vvsa_4], Role: TRANSLATION
Page 156, Line: (9) a.  tumun ririn = ten kiem, Role: SOURCE
Page 156, Line: child tall=at run, Role: GLOSS
Page 156, Line: ‘The tall child runs.’, Role: TRANSLATION
Page 156, Line: b.  tumun kiem = ten ririn, Role: SOURCE
Page 156, Line: child run=at tall, Role: GLOSS
Page 156, Line: ‘The running child is tall.’ [elic_adj_45], Role: TRANSLATION
Page 156, Line: (10) a.  don mun = ten wandi=et ka bisa na=ta, Role: SOURCE
Page 156, Line: thing rotten=at like_this=irr 2sg can eat=nfin, Role: GLOSS
Page 156, Line: ‘You can eat rotten things like this.’ [narr39_7:35], Role: TRANSLATION
Page 156, Line: b.  tumun tur = ten ma elao melalu, Role: SOURCE
Page 156, Line: child fall=at 3sg down.loc sit, Role: GLOSS
Page 156, Line: ‘The fallen child (he) sits on the floor.’ [elic_vvsa_12], Role: TRANSLATION

In [97]:
for row in final_roles:
    print(f"Page {row['page_num']}: {row['bline']['text']} --> {row['role']}")

Page 20: (1) hukat kon anggon yuwa --> SOURCE
Page 20: jaring_ikan satu milik_saya ini --> GLOSS
Page 20: ‘jaring ikan milik saya satu ini’ --> TRANSLATION
Page 21: (2) kaskas et-eir --> SOURCE
Page 21: burung_camar hidup-dua --> GLOSS
Page 21: ‘dua burung camar’ --> TRANSLATION
Page 22: (3) ma se guru --> SOURCE
Page 22: dia sudah guru --> GLOSS
Page 22: ‘Dia sudah (menjadi seorang) guru.’ --> TRANSLATION
Page 22: (4) ma me --> SOURCE
Page 22: dia itu --> GLOSS
Page 22: ‘Itu dia.’ --> TRANSLATION
Page 22: (5) im kansuor --> SOURCE
Page 22: pisang empat --> GLOSS
Page 22: ‘Ada empat pisang.’ --> TRANSLATION
Page 22: (6) ka-mun narabir-in --> SOURCE
Page 22: kamu-jangan berteriak-jangan --> GLOSS
Page 22: ‘Janganlah kamu berteriak!’ --> TRANSLATION
Page 23: (7) an me watko nawanggar --> SOURCE
Page 23: saya topik disini tunggu --> GLOSS
Page 23: ‘Untuk saya, saya menunggu di sini.’ --> TRANSLATION
Page 23: (8) an-a watko mu-a metko --> SOURCE
Page 23: saya-fokus disini mereka-fokus disana --> GLOSS
Page 23: ‘ Saya  ada di sini,  mereka  ada di sana.’ --> TRANSLATION
Page 52: (1) bal se sor=at koraru --> SOURCE
Page 52: dog iam fish=obj bite --> GLOSS
Page 52: ‘The dog has bitten the fish.’ [stim2_3:45] --> TRANSLATION
Page 52: (2) mu kiem --> SOURCE
Page 52: 3pl run --> GLOSS
Page 52: ‘They run.’ [narr40_15:26] --> TRANSLATION
Page 52: (3) ma reitkon purap-i an=at kamat=et --> SOURCE
Page 52: 3sg hundred fifty-objqnt 1sg=obj send=irr --> GLOSS
Page 52: ‘He sent me one hundred and fifty [thousand rupiah].’ [conv12_3:09] --> TRANSLATION
Page 53: (4) mu pas sem=ten=at koup --> SOURCE
Page 53: 3pl woman afraid-adj=obj hug --> GLOSS
Page 53: ‘They hugged the scared woman.’ [elic_adj19_8] --> TRANSLATION
Page 56: (5) an se toni min=kin --> SOURCE
Page 56: 1sg iam want sleep=vol --> GLOSS
Page 56: ‘I already wanted to sleep.’ [narr32_0:18] --> TRANSLATION
Page 57: (6) Ma toni: “Eh, sor wa me tamandi, pi parinet ye, pi parairet, --> SOURCE
Page 57: ma toni eh sor wa me tamandi pi parin=et ye pi parair=et --> GLOSS
Page 57: 3sg say hey fish prox top how 1pl.incl sell=irr or 1pl.incl split=irr --> GLOSS
Page 57: siraet.” --> SOURCE
Page 57: sira=et --> GLOSS
Page 57: salt=irr --> GLOSS
Page 57: ‘He said: “Hey, these fish, how [should we treat them]? Do we sell them, --> TRANSLATION
Page 57: or do we split and salt them?”’ [narr8_5:34] --> TRANSLATION
Page 62: (1) /pep/ ‘pig’ + /at/ ‘obj’ [ˈpewat̚] ‘pig.obj’ --> SOURCE
Page 62: /et/ ‘canoe’ + /at/ ‘obj’ [ˈerat̚] ‘canoe.obj’ --> SOURCE
Page 62: /tektek/ ‘knife’ + /at/ ‘obj’ [ˈtɛkteat̚] ‘knife.obj’ --> SOURCE
Page 62: (2) /saˈren/ ‘aground’ + /ten/ ‘at’ [wat saˈrɛndɛn] ‘old coconut’ --> SOURCE
Page 62: /kalaˈmaŋ/ ‘Karas’ + /ko/ ‘loc’ [kalaˈmaŋgo] ‘on Karas’ --> SOURCE
Page 62: /seram/ ‘Seram’ + /ka/ ‘lat’ [seramga] ‘from/to Seram’ --> SOURCE
Page 62: /leŋ/ ‘village’ + /ca/ ‘2sg.poss’ [ˈlɛŋɟa] ‘your village’ --> SOURCE
Page 62: (3) /ˈtan/ ‘arm; hand’ + /ko/ loc [ˈtaŋgo] ‘in hand; on arm’ --> SOURCE
Page 63: (4) /ko/ ‘appl’ + /kaŋgirar/ ‘face’ [kokaŋgirar] ‘to face someone’ --> COMMENT
Page 63: (5) ma ror cicaun=at pue --> SOURCE
Page 63: 3sg tree small=obj hit --> GLOSS
Page 63: ‘He/she hits the small tree.’ --> TRANSLATION
Page 63: (6) ma=bon kiun=bon se bot --> SOURCE
Page 63: 3sg=com wife.3sg.poss=com iam go --> GLOSS
Page 63: ‘He and his wife have gone.’ --> TRANSLATION
Page 63: (7) ka pasa=at sasul=ki na --> SOURCE
Page 63: 2sg rice=obj spoon=ins consume --> GLOSS
Page 63: ‘You eat rice with a spoon.’ --> TRANSLATION
Page 63: (8) canam kewe=at kiun=ki paruo --> SOURCE
Page 63: man house=obj wife.3sg.poss=ben make --> GLOSS
Page 63: ‘The man makes a house for his wife.’ --> TRANSLATION
Page 64: (9) ma per=kap --> SOURCE
Page 64: 3sg water=sim --> GLOSS
Page 64: ‘It’s like water.’ --> TRANSLATION
Page 64: (10) kasamin-an kewe=ko --> SOURCE
Page 64: bird-1sg.poss house=loc --> GLOSS
Page 64: ‘My bird is in the house.’ --> TRANSLATION
Page 64: (11) tumun wilak=ka bot --> SOURCE
Page 64: child sea=lat go --> GLOSS
Page 64: ‘The child goes to the sea.’ --> TRANSLATION
Page 64: (12) bal muap-un --> SOURCE
Page 64: dog food-3poss --> GLOSS
Page 64: ‘the dog’s food’ --> TRANSLATION
Page 64: (13) bal eir kanggeit --> SOURCE
Page 64: dog two play --> GLOSS
Page 64: ‘Two dogs play.’ --> TRANSLATION
Page 64: (14) bal anggon kanggeit --> SOURCE
Page 64: dog 1sg.prox play --> GLOSS
Page 64: ‘My dog plays.’ --> TRANSLATION
Page 64: (15) bal wa kanggeit --> SOURCE
Page 64: dog prox play --> GLOSS
Page 64: ‘This dog plays.’ --> TRANSLATION
Page 64: (16) bal kotur-ten kanggeit --> SOURCE
Page 64: dog dirty-at play --> GLOSS
Page 64: ‘A dirty dog plays.’ --> TRANSLATION
Page 65: (17) ki pi=at konawaruo --> SOURCE
Page 65: 2pl 1pl.incl=obj forget --> GLOSS
Page 65: ‘You forget us.’ --> TRANSLATION
Page 65: (18) ma-tain gonggin --> SOURCE
Page 65: 3sg-alone know --> GLOSS
Page 65: ‘Only she knows.’ --> TRANSLATION
Page 65: (19) Ramina ma-hutak bara --> SOURCE
Page 65: Ramina 3sg-alone descend --> GLOSS
Page 65: ‘Only Ramina comes down.’ --> TRANSLATION
Page 65: (20) in-naninggan bo kelek=ko --> SOURCE
Page 65: 1pl.excl-all go mountain=loc --> GLOSS
Page 65: ‘We all go to the mountain.’ --> TRANSLATION
Page 65: (21) mu muin=at jie --> SOURCE
Page 65: 3pl 3pl.poss=obj get --> GLOSS
Page 65: ‘They get theirs.’ --> TRANSLATION
Page 65: (22) Safril esun Juaria tara-un=at gerket --> SOURCE
Page 65: Safril father.3poss Juaria grandfather-3poss=obj ask --> GLOSS
Page 65: ‘Safril’s father asks Juaria’s grandfather.’ --> TRANSLATION
Page 67: (23) tumtum per-an anggon na --> SOURCE
Page 67: children water-1sg.poss 1sg.poss consume --> GLOSS
Page 67: ‘Children drink my water.’ --> TRANSLATION
Page 67: (24) guru leng=kin --> SOURCE
Page 67: teacher village=poss --> GLOSS
Page 67: ‘the teacher of the village/the village teacher’ --> TRANSLATION
Page 68: (25) wangga mei --> SOURCE
Page 68: prox.lat come.imp --> GLOSS
Page 68: ‘Come here!’ --> TRANSLATION
Page 68: (26) an don met mormor --> SOURCE
Page 68: 1sg thing dist.obj hide --> GLOSS
Page 68: ‘I hide that thing.’ --> TRANSLATION
Page 68: (27) mu amdir yawet paruot=kin --> SOURCE
Page 68: 3pl garden down.obj make=vol --> GLOSS
Page 68: ‘They want to make that garden down there.’ --> TRANSLATION
Page 68: (28) pulor opa tamatko --> SOURCE
Page 68: betel_vine ana where --> GLOSS
Page 68: ‘Where is that betel vine (that we just saw or talked about)?’ --> TRANSLATION
Page 69: (29) buok  ‘betel’ → buokbuok  ‘to chew betel’ --> SOURCE
Page 69: (30) per-na, wat-na --> SOURCE
Page 69: water-consume, coconut-consume --> GLOSS
Page 69: ‘to drink water, to eat coconut’ --> TRANSLATION
Page 69: (31) kerkap  ‘to be red’ → kerkap∼kap  ‘to be very red’ --> SOURCE
Page 69: (32) paruo  ‘to do’ → paruo∼paruo  ‘to usually do; to do for a long time’ --> SOURCE
Page 69: (33) winyal  ‘to fish’ → winyal∼winyal  ‘to fish for a long time; to fish in different --> SOURCE
Page 69: places in an area’ --> SOURCE
Page 70: (34) ma-tain se un-deir=i luk --> SOURCE
Page 70: 3sg-alone iam refl-bring=plnk come --> GLOSS
Page 70: ‘She came herself.’ (Lit. ‘She brought herself coming.’) [narr24_5:33] --> TRANSLATION
Page 70: (35) mu nau=tu --> SOURCE
Page 70: 3pl recp=hit --> GLOSS
Page 70: ‘They hit each other.’ --> TRANSLATION
Page 70: (36) mier torpes-ko=ar --> SOURCE
Page 70: 3du shell-appl-dive --> GLOSS
Page 70: ‘They two dive for shells.’ --> TRANSLATION
Page 70: (37) mu ror=at di=maruan --> SOURCE
Page 70: 3pl wood=obj caus=move_seawards --> GLOSS
Page 70: ‘They move the wood seawards.’ --> TRANSLATION
Page 70: (38) in kiem --> SOURCE
Page 70: 1pl.excl flee --> GLOSS
Page 70: ‘We flee.’ --> TRANSLATION
Page 70: (39) in sor=at potma --> SOURCE
Page 70: 1pl.excl fish=obj cut --> GLOSS
Page 70: ‘We cut fish.’ --> TRANSLATION
Page 71: (40) mu tok watko --> SOURCE
Page 71: 3pl still there --> GLOSS
Page 71: ‘They are still there.’ --> TRANSLATION
Page 71: (41) tumun kon guru --> SOURCE
Page 71: child one teacher --> GLOSS
Page 71: ‘One child is a teacher.’ --> TRANSLATION
Page 71: (42) kewe-an eir --> SOURCE
Page 71: house-3poss two --> GLOSS
Page 71: ‘I have two houses.’ --> TRANSLATION
Page 72: (43) ma ecien=i bara --> SOURCE
Page 72: 3sg return=plnk descend --> GLOSS
Page 72: ‘He returns down.’ --> TRANSLATION
Page 72: (44) ma ecien=i kewe=ko --> SOURCE
Page 72: 3sg return=plnk house=loc --> GLOSS
Page 72: ‘He returns home.’ --> TRANSLATION
Page 72: (45) ma sara bo karop-un osa-t=ko --> SOURCE
Page 72: 3sg ascend go branch-3poss up-t=loc --> GLOSS
Page 72: ‘He climbed up to the branch up there.’ [conv12_16:39] --> TRANSLATION
Page 72: (46) ka mu ∅= te mu na --> SOURCE
Page 72: 2sg 3pl give=nfin 3pl consume --> GLOSS
Page 72: ‘You give [the food] to them, they eat. [conv11_5:18] --> TRANSLATION
Page 73: (47) an se tumun-an=at boubou --> SOURCE
Page 73: 1sg iam child-1sg.poss=obj bathe --> GLOSS
Page 73: ‘I already bathed my child.’ --> TRANSLATION
Page 73: (48) an se tumun-an=at boubou=nin --> SOURCE
Page 73: 1sg iam child-1sg.poss=obj bathe=neg --> GLOSS
Page 73: ‘I’m not bathing my child anymore.’ --> TRANSLATION
Page 73: (49) an tok tumun-an=at boubou --> SOURCE
Page 73: 1sg still child-1sg.poss=obj bathe --> GLOSS
Page 73: ‘I’m still bathing my child.’ --> TRANSLATION
Page 73: (50) an tok tumun-an=at boubou=nin --> SOURCE
Page 73: 1sg yet child-1sg.poss=obj bathe=neg --> GLOSS
Page 73: ‘I haven’t yet bathed my child.’ --> TRANSLATION
Page 73: (51) canam me me ma kip=at sem --> SOURCE
Page 73: man dist top 3sg snake=obj afraid --> GLOSS
Page 73: ‘As for that man, he is afraid of snakes.’ --> TRANSLATION
Page 73: (52) canam me me kip=at sem --> SOURCE
Page 73: man dist top snake=obj afraid --> GLOSS
Page 73: ‘That man is afraid of snakes.’ --> TRANSLATION
Page 73: (53) ka neba=at=a paruo --> SOURCE
Page 73: 2sg what=obj=foc do --> GLOSS
Page 73: ‘What are you doing?’ --> TRANSLATION
Page 80: (1) bilabials: /p – b – m – w/ --> COMMENT
Page 80: pol  ‘sap’ [pol] --> COMMENT
Page 80: bol  ‘mouth’ [bol] --> COMMENT
Page 80: mul-  ‘side’ [mul] --> COMMENT
Page 80: wol  ‘family’ [wol] --> COMMENT
Page 80: (2) alveolars: /t – d – s – n – r – l/ --> COMMENT
Page 80: tan  ‘arm’ [tan] --> COMMENT
Page 80: dan  ‘to bury’ [dan] --> COMMENT
Page 80: sanam  ‘scabies’ [ˈsa.nam] --> COMMENT
Page 80: na  ‘to consume’ [na] --> COMMENT
Page 80: ra  ‘to hear’ [ra] --> COMMENT
Page 80: lam  ‘soft coral’ [lam] --> COMMENT
Page 139: (1) in pep-mang- un = at paruon --> SOURCE
Page 139: 1pl.excl pig-language-3poss=obj make --> GLOSS
Page 139: ‘We’re making pig’s language [= ugly language].’ [conv1_7:15] --> TRANSLATION
Page 139: (2) A:  naman=a se bot --> SOURCE
Page 139: who=foc iam go --> GLOSS
Page 139: ‘Who has already gone?’ --> TRANSLATION
Page 139: B:  *an se --> SOURCE
Page 139: 1sg iam --> GLOSS
Page 139: ‘Me.’ [elic] --> TRANSLATION
Page 139: (3) mat dan=i koyet se ecien=i sara --> SOURCE
Page 139: 3sg.obj bury=plnk finish iam return=plnk ascend --> GLOSS
Page 139: ‘After burying him [we] went back up.’ [narr2_0:34] --> TRANSLATION
Page 140: (4) Emun se... se wanir. --> SOURCE
Page 140: emun se se wanir --> GLOSS
Page 140: mother.3poss iam iam twice --> GLOSS
Page 140: ‘Her mother [did it] already... already twice.’ [narr25_1:45] --> TRANSLATION
Page 140: (5) A:  ka se bot --> SOURCE
Page 140: 2sg iam go --> GLOSS
Page 140: ‘Have you gone already?’ --> TRANSLATION
Page 140: B:  *se --> SOURCE
Page 140: iam --> GLOSS
Page 140: ‘Yes/already.’ --> TRANSLATION
Page 140: (6) A:  ki se kai=at rep --> SOURCE
Page 140: 2pl iam firewood=obj get --> GLOSS
Page 140: ‘Did you already get firewood?’ --> TRANSLATION
Page 140: B:  tok --> SOURCE
Page 140: not.yet --> GLOSS
Page 140: ‘Not yet.’ [conv9_31:24] --> TRANSLATION
Page 145: (7) a. /ˌmisilˈmisil/ ‘cement floor’ --> SOURCE
Page 145: b. /ˈwuorˌwuor/ ‘to dream’ --> SOURCE
Page 145: c. /nokˈnok/ ‘to whisper’ (cf. /noˈkidak/ ‘to be silent’) --> SOURCE
Page 145: d. /boukˈbouk/ ‘to bark’ --> SOURCE
Page 145: e. /korˈtaptap/ ‘to cut out’ --> SOURCE
Page 145: f. /ˈmarmar/ ‘to walk’ --> SOURCE
Page 145: g. /ˌsiŋa(t)ˈsiŋat/ ‘ant’ --> SOURCE
Page 145: h. /paŋˈgawaŋˌga/ ‘leech’ --> SOURCE
Page 147: (8) an se koi yal yal yal tebol-suban war=i war=i --> SOURCE
Page 147: 1sg iam again paddle paddle paddle reef_edge-fish fish=plnk fish=plnk --> GLOSS
Page 147: eh sor nat=nin --> SOURCE
Page 147: int.e fish consume=neg --> GLOSS
Page 147: ‘I paddled and paddled again, fished at the reef edge, fished and fished, --> TRANSLATION
Page 147: the fish didn’t bite.’ [narr8_1:02] --> TRANSLATION
Page 147: (9) warkin naman=et pi wandi siktak∼tak=i tiri∼tiri --> SOURCE
Page 147: tide deep=irr 1pl.excl like_this slow∼ints=plnk sail∼prog --> GLOSS
Page 147: tiri∼tiri --> SOURCE
Page 147: sail∼prog --> GLOSS
Page 147: ‘When the tide is deep we sail slowly like this.’ [conv1_1:33] --> TRANSLATION
Page 148: (10) ma-mun ma neba ewa∼wa∼ewawa =in [ ... ]  ewa∼wa∼ewawa --> SOURCE
Page 148: 3sg-proh 3sg ph talk∼prog∼prog=proh talk∼prog∼prog --> GLOSS
Page 148: ‘She shouldn’t talk, talk [disturbing].’ [conv10_15:23] --> TRANSLATION
Page 148: (11) yap_seran-un --> SOURCE
Page 148: yam-3poss --> GLOSS
Page 148: ‘their yam’ [conv10_16:03] --> TRANSLATION
Page 148: (12) min-kalot=at kasi bersi --> SOURCE
Page 148: sleep-room=obj give clean --> GLOSS
Page 148: ‘clean the bedroom’ [narr41_0:13] --> TRANSLATION
Page 149: (13) a.  an ˈperat ˈna --> SOURCE
Page 149: an per=at na --> GLOSS
Page 149: 1sg water=obj consume --> GLOSS
Page 149: ‘I drink water.’ --> TRANSLATION
Page 149: b.  an ˈperna --> SOURCE
Page 149: an per-na --> GLOSS
Page 149: 1sg water-consume --> GLOSS
Page 149: ‘I drink water.’ [elic_inc_2] --> TRANSLATION
Page 149: (14) Juaria se muawaruoni koyet. --> SOURCE
Page 149: Juaria se muap-paruon=i koyet --> GLOSS
Page 149: Juaria iam food-make=plnk finish --> GLOSS
Page 149: ‘Juaria has cooked.’ [narr7_12:08] --> TRANSLATION
Page 149: (15) Mama Tua kureraparuo. --> SOURCE
Page 149: Mama Tua kurera-paruo --> GLOSS
Page 149: Mama Tua basket-make --> GLOSS
Page 149: ‘Mama Tua making a basket.’ [stim42_4:26] --> TRANSLATION
Page 150: (16) dudan-mur-un --> SOURCE
Page 150: sibling-kin.pl-3poss --> GLOSS
Page 150: ‘his/her siblings’ --> TRANSLATION
Page 150: (17) ma sontum leng-et=at merengguen --> SOURCE
Page 150: 3sg person village-nmlz=obj gather --> GLOSS
Page 150: ‘He gathered the village people.’ [narr27_3:17] --> TRANSLATION
Page 150: (18) don wa me se amkeit-et=kongga --> SOURCE
Page 150: thing prox top iam give_birth-nmlz=an.lat --> GLOSS
Page 150: ‘This thing comes from the birth parent.’ [conv20_38:53] --> TRANSLATION
Page 151: (19) an kewe= at=a kon-i paruo --> SOURCE
Page 151: 1sg house=obj=foc one-objqnt make --> GLOSS
Page 151: ‘I made a house.’ [narr41_0:45] --> TRANSLATION
Page 151: (20) ka me or= ko=te --> SOURCE
Page 151: 2sg top back=loc=imp --> GLOSS
Page 151: ‘You’re in the back!’ [narr19_5:00] --> TRANSLATION
Page 154: (1) mu toni kalis=kin --> SOURCE
Page 154: 3pl think rain=vol --> GLOSS
Page 154: ‘They think it will rain.’ [narr22_4:04] --> TRANSLATION
Page 155: (2) teun ten --> SOURCE
Page 155: fruit bad --> GLOSS
Page 155: ‘The fruits are bad.’ [narr13_4:14] --> TRANSLATION
Page 155: (3) mu kiem --> SOURCE
Page 155: 3pl run --> GLOSS
Page 155: ‘They run.’ [narr40_15:26] --> TRANSLATION
Page 155: (4) emun tumun=at narorar --> SOURCE
Page 155: mother child=obj take_by_hand --> GLOSS
Page 155: ‘The mother takes the child by the hand.’ [stim4_4:47] --> TRANSLATION
Page 155: (5) mu kawir-un=at mat naunak --> SOURCE
Page 155: 3pl hat-3poss=obj 3sg.obj show --> GLOSS
Page 155: ‘They showed him the hat.’ [stim31_2:30] --> TRANSLATION
Page 155: (6) in se tiri yecie --> SOURCE
Page 155: 1pl.excl iam sail return --> GLOSS
Page 155: ‘We sailed back.’ [narr44_2:56] --> TRANSLATION
Page 155: (7) ma kahen=i baran --> SOURCE
Page 155: 3sg far=plnk descend --> GLOSS
Page 155: ‘He goes down far.’ [stim44_0:32] --> TRANSLATION
Page 155: (8) a.  ror-potma --> SOURCE
Page 155: wood-cut --> GLOSS
Page 155: ‘to cut wood’ [narr7_4:13] --> TRANSLATION
Page 155: b.  ror paramuan= ten --> SOURCE
Page 155: wood cut=at --> GLOSS
Page 155: ‘cut wood (wood that is cut)’ [elic_vvsa_4] --> TRANSLATION
Page 156: (9) a.  tumun ririn = ten kiem --> SOURCE
Page 156: child tall=at run --> GLOSS
Page 156: ‘The tall child runs.’ --> TRANSLATION
Page 156: b.  tumun kiem = ten ririn --> SOURCE
Page 156: child run=at tall --> GLOSS
Page 156: ‘The running child is tall.’ [elic_adj_45] --> TRANSLATION
Page 156: (10) a.  don mun = ten wandi=et ka bisa na=ta --> SOURCE
Page 156: thing rotten=at like_this=irr 2sg can eat=nfin --> GLOSS
Page 156: ‘You can eat rotten things like this.’ [narr39_7:35] --> TRANSLATION
Page 156: b.  tumun tur = ten ma elao melalu --> SOURCE
Page 156: child fall=at 3sg down.loc sit --> GLOSS
Page 156: ‘The fallen child (he) sits on the floor.’ [elic_vvsa_12] --> TRANSLATION
Page 156: c.  tumun tiri = ten ladan kerkap=ten=at sabur --> SOURCE
Page 156: child run=at shirt red=at=obj wear --> GLOSS
Page 156: ‘The running child wears a red shirt.’ [elic_vvsa_13] --> TRANSLATION
Page 156: d.  tumun doa=at nabaca = ten ladan kerkap=ten=at sabur --> SOURCE
Page 156: child prayer=obj read=at shirt red=at=obj wear --> GLOSS
Page 156: ‘The child that is reading a prayer wears a red shirt.’ [elic_vvsa_15] --> TRANSLATION
Page 156: (11) mu fiber temun kerunggo --> SOURCE
Page 156: 3pl fibre_boat big inside --> GLOSS
Page 156: ‘They are in a big fibre boat.’ [conv14_10:45] --> TRANSLATION
Page 157: (12) a. [ tumun tabusik wa ] NP --> SOURCE
Page 157: child short prox --> GLOSS
Page 157: ‘this short child’ --> TRANSLATION
Page 157: b. [ tumun wa ] NP [ tabusik ] Pred --> SOURCE
Page 157: child prox short --> GLOSS
Page 157: ‘This child is short. --> TRANSLATION
Page 157: c. [ ma ] NP [ tabusik ] Pred --> SOURCE
Page 157: 3sg short --> GLOSS
Page 157: ‘He is short.’ [elic_adj] --> TRANSLATION
Page 157: (13) esnem se lalat --> SOURCE
Page 157: man iam dead --> GLOSS
Page 157: ‘The man is dead.’ [narr22_2:52] --> TRANSLATION
Page 157: (14) emun tumun=at narorar --> SOURCE
Page 157: mother.3poss child=obj take_by_hand --> GLOSS
Page 157: ‘The mother takes the child by the hand.’ [stim4_4:47] --> TRANSLATION
Page 158: (15) [ pebis towari∼wari ] NP marua --> SOURCE
Page 158: woman young∼red move_seawards --> GLOSS
Page 158: ‘The young women went towards sea.’ [narr19_4:22] --> TRANSLATION
Page 158: (16) [ pasa lu=ten ] NP mambon --> SOURCE
Page 158: rice cold=at exist --> GLOSS
Page 158: ‘Is there cold rice?’ [conv10_3:36] --> TRANSLATION
Page 158: (17) [ sontum reidak ] NP toni mu [ ... ] --> SOURCE
Page 158: person many say 3pl --> GLOSS
Page 158: ‘Many people say they [...].’ [conv16_1:04] --> TRANSLATION
Page 158: (18) [ tumtum karuok ] NP marmar=i mia --> SOURCE
Page 158: children four walk=plnk come --> GLOSS
Page 158: ‘Four children come walking.’ [stim31_1:46] --> TRANSLATION
Page 158: (19) a.  Malik kewe-un --> SOURCE
Page 158: Malik house-3poss --> GLOSS
Page 158: ‘Malik’s house’ [stim42_10:46] --> TRANSLATION
Page 158: b.  kewe anggas-un --> SOURCE
Page 158: house door-3poss --> GLOSS
Page 158: ‘the house’s door’ [stim42_12:29] --> TRANSLATION
Page 158: (20) et-an=at --> SOURCE
Page 158: canoe-1sg.poss=obj --> GLOSS
Page 158: ‘my canoe’ [narr41_1:05] --> TRANSLATION
Page 160: (21) in ikon tok patin=nin=ten --> SOURCE
Page 160: 1pl.excl some yet wound=neg=at --> GLOSS
Page 160: ‘Some of us are not wounded yet.’ [narr22_7:10] --> TRANSLATION
Page 160: (22) an yuwa me warpas=a an=at melebor=ta --> SOURCE
Page 160: 1sg prox top witch=foc 1sg=obj move_to_side=nfin --> GLOSS
Page 160: ‘As for me, the witch shoved me aside.’ [narr23_4:56] --> TRANSLATION
Page 160: (23) ma main=at na --> SOURCE
Page 160: 3sg 3poss=obj consume --> GLOSS
Page 160: ‘He drinks his [one/drink].’ [stim4_2:07] --> TRANSLATION
Page 160: (24) ma canam mat koluk --> SOURCE
Page 160: 3sg man 3sg.obj meet --> GLOSS

In [98]:
missing_parrallel_lines = []
page_nos = [188,229,278,452]
for page in all_merged_lines:
    page_no = page["page_num"]
    if page_no not in page_nos:
        continue
    print("--- Page", page_no, "---")
    for line_no,line in enumerate(page["lines"]):
        x0 = line["x0"]
        text = line["text"]
        bbox = (line["x0"], line["y0"], line["x1"], line["y1"])
        line["bbox"] = bbox
        #print(text,x0)
        #print(text, x0)
        values = [99,113,142,85]
        if any(abs(x0 - v) < 5 for v in values) and "LibertinusSerif" in line["common_font_style"]:
            # Check if this line is in final_roles
            found = False
            for row in final_roles:
                if row["page_num"] == page_no and row["bline"]["text"] == text:
                    found = True
                    #print("FOUND PARALLEL LINE:")
                    print(f" --- Page {page_no}: {text} (x0={x0})")
                    break
            if not found:
                missing_parrallel_lines.append({
                    "page_num": page_no,
                    "bline": {
                        "page_num": page_no,
                        "line_no": line_no,
                        "text": text,
                        "bbox": bbox,
                        "line": line,
                        "start": False
                    },
                    
                })
                #print("MISSING PARALLEL LINE!")
                print(f"Page {page_no}: {text} (x0={x0})")

--- Page 188 ---
Page 188: c.  kor kasir (x0=99.95100402832031)
Page 188: leg joint (x0=114.04000091552734)
Page 188: ‘ankle’ (x0=113.16699981689453)
Page 188: d.  kor-pak (x0=99.0999984741211)
Page 188: leg-moon (x0=114.04000091552734)
Page 188: ‘knee’ (x0=113.16699981689453)
Page 188: For many right-headed compounds, the choice between using or not using  -un (x0=80.35800170898438)
 --- Page 188: a.  kokok-nar (x0=99.63400268554688)
 --- Page 188: chicken-egg (x0=114.04000091552734)
 --- Page 188: ‘chicken egg’ (x0=113.16699981689453)
 --- Page 188: b.  kokok nar-un (x0=99.45999908447266)
 --- Page 188: chicken egg (x0=114.04000091552734)
 --- Page 188: ‘chicken egg’ (x0=113.16699981689453)
 --- Page 188: b.  lempuang  ‘island’ → lempuangpuang  ‘islands’ (x0=99.45999908447266)
 --- Page 188: c.  tumun  ‘child’ → tumtum  ‘children’ (x0=99.95100402832031)
--- Page 229 ---
Page 229: 57 purap talinramandalin (x0=85.5469970703125)
Page 229: 98 putkaninggonie talinirie (x0=85.5469970703125)
Page 229: ‘two thousand four hundred fifty and six’ (x0=142.23899841308594)
Page 229: 8721 ripirie reitramandalin purir ba kon (x0=85.5469970703125)
Page 229: ‘eight thousand seven hundred twenty and one’ (x0=142.23899841308594)
Page 229: 72,568 ripi putramandalin talinir reirap putraman talinirie (x0=85.5469970703125)
Page 229: ‘seventy and two thousand five hundred sixty and eight’ (x0=142.23899841308594)
Page 229: 526,389 ripi reirap purir ba raman reitkaruok putirie talinkaninggonie (x0=85.5469970703125)
Page 229: ‘five hundred and twenty and six thousand three hundred eighty (x0=142.23899841308594)
Page 229: and nine’ (x0=142.23899841308594)
Page 229: 1,500,000 juta kon ripi reirap (x0=85.5469970703125)
Page 229: ‘one million five hundred thousand’ (x0=142.23899841308594)
 --- Page 229: ‘one thousand fifty’ (x0=142.23899841308594)
Page 229: 50,000 ripi purap (x0=85.5469970703125)
Page 229: ‘fifty thousand’ (x0=142.23899841308594)
Page 229: 1100 ripion reitkon (x0=85.5469970703125)
Page 229: ‘one thousand one hundred’ (x0=142.23899841308594)
Page 229: 100,000 ripi reitkon (x0=85.5469970703125)
Page 229: ‘one hundred thousand’ (x0=142.23899841308594)
--- Page 278 ---
Page 278: b.  mu tok bo jie t =nin (x0=99.45999908447266)
Page 278: 3pl yet go buy=neg (x0=114.04000091552734)
Page 278: ‘They didn’t go buy yet.’ [conv10_6:18] (x0=113.16699981689453)
Page 278: Table 11.1: Behaviour of regular verbs under inflection (x0=137.4929962158203)
Page 278: =i  plnk taot=i muap=i ewa=i (x0=110.85900115966797)
Page 278: =et  irr taot=et muap=et ewa=et (x0=110.85899353027344)
Page 278: =kin  vol taot=kin muap=kin ewa=kin (x0=110.85899353027344)
Page 278: =nin  neg taot=nin muap=nin ewa=nin (x0=110.85899353027344)
Page 278: =in  proh taot=in muap=in ewa=in (x0=110.85899353027344)
Page 278: imperative taot=te muap=te ewa=te (x0=110.85899353027344)
Page 278: A sizeable minority of Kalamang verbs, 185 out of 650 in the corpus, are vowel- (x0=80.35800170898438)
--- Page 452 ---
Page 452: In (46), the speaker turns  adeh  int.pej into a verb while scolding their child (x0=80.35800170898438)
 --- Page 452: 3sg say int.pej quot 2sg-proh int.pej=proh consume consume (x0=97.30000305175781)
 --- Page 452: na na (x0=96.88502502441406)
 --- Page 452: consume consume (x0=96.88502502441406)
 --- Page 452: ‘She said: “Oh no.” [I’m like:] “Don’t you “oh no” me, eat, eat, eat, eat!”’ (x0=96.01202392578125)
Page 452: Some  is used for encouragement, often in a slightly annoyed fashion, when (x0=80.35800170898438)
 --- Page 452: Sunday roof-nail enc work much-ten top (x0=96.91799926757812)
 --- Page 452: ‘Of course we nail the roof on Sunday, there’s a lot of work.’ [narr3_1:04] (x0=96.01199340820312)
 --- Page 452: tobacco dist.obj smoke=nfin taste how good or good enc (x0=97.25599670410156)
 --- Page 452: 2014 (x0=96.885009765625)
 --- Page 452: 2014 (x0=96.885009765625)
 --- Page 452: “That tobacco [you’re] smoking, how does it taste, good, or what?” “Of (x0=95.66300964355469)
 --- Page 452: course it’s good, it’s from 2014!” [narr16_3:11] (x0=96.885009765625)
Page 452: Another interjection with a similar function to  some  is  mera , which is used (x0=80.35800170898438)
 --- Page 452: emph 3pl=foc dig maybe (x0=114.48699951171875)
 --- Page 452: ‘Oh maybe they dug.’ (x0=113.16699981689453)
 --- Page 452: B:  o ge mera sontum ruot=nin (x0=98.03099822998047)
 --- Page 452: emph no int person dig=neg (x0=114.04000091552734)
 --- Page 452: ‘Of course not, people didn’t dig.’ [conv1_3:39] (x0=113.1669921875)

In [99]:
manual_roles = "SGTSGTCCCSTSTSTTSTSTSTSTSGTCCCCCCCCCCTC"
manual_roles = [x for x in manual_roles]
mapping = {
    "S": "SOURCE",
    "G": "GLOSS",
    "T": "TRANSLATION",
    "C": "COMMENT"
}
manual_missing_parallel_lines_classification = [mapping[x] for x in manual_roles]

In [100]:
len(manual_missing_parallel_lines_classification), len(missing_parrallel_lines)

(39, 39)

In [101]:
missing_parrallel_lines_filtered = []

for i,row in enumerate(missing_parrallel_lines):

    print(f"Page {row['page_num']}: {row['bline']['text']} ---> {manual_missing_parallel_lines_classification[i]}")
    if manual_missing_parallel_lines_classification[i] != "COMMENT":
        row["role"] = manual_missing_parallel_lines_classification[i]
        missing_parrallel_lines_filtered.append(row)

Page 188: c.  kor kasir ---> SOURCE
Page 188: leg joint ---> GLOSS
Page 188: ‘ankle’ ---> TRANSLATION
Page 188: d.  kor-pak ---> SOURCE
Page 188: leg-moon ---> GLOSS
Page 188: ‘knee’ ---> TRANSLATION
Page 188: For many right-headed compounds, the choice between using or not using  -un ---> COMMENT
Page 229: 57 purap talinramandalin ---> COMMENT
Page 229: 98 putkaninggonie talinirie ---> COMMENT
Page 229: ‘two thousand four hundred fifty and six’ ---> SOURCE
Page 229: 8721 ripirie reitramandalin purir ba kon ---> TRANSLATION
Page 229: ‘eight thousand seven hundred twenty and one’ ---> SOURCE
Page 229: 72,568 ripi putramandalin talinir reirap putraman talinirie ---> TRANSLATION
Page 229: ‘seventy and two thousand five hundred sixty and eight’ ---> SOURCE
Page 229: 526,389 ripi reirap purir ba raman reitkaruok putirie talinkaninggonie ---> TRANSLATION
Page 229: ‘five hundred and twenty and six thousand three hundred eighty ---> TRANSLATION
Page 229: and nine’ ---> SOURCE
Page 229: 1,500,000 juta kon ripi reirap ---> TRANSLATION
Page 229: ‘one million five hundred thousand’ ---> SOURCE
Page 229: 50,000 ripi purap ---> TRANSLATION
Page 229: ‘fifty thousand’ ---> SOURCE
Page 229: 1100 ripion reitkon ---> TRANSLATION
Page 229: ‘one thousand one hundred’ ---> SOURCE
Page 229: 100,000 ripi reitkon ---> TRANSLATION
Page 229: ‘one hundred thousand’ ---> SOURCE
Page 278: b.  mu tok bo jie t =nin ---> GLOSS
Page 278: 3pl yet go buy=neg ---> TRANSLATION
Page 278: ‘They didn’t go buy yet.’ [conv10_6:18] ---> COMMENT
Page 278: Table 11.1: Behaviour of regular verbs under inflection ---> COMMENT
Page 278: =i  plnk taot=i muap=i ewa=i ---> COMMENT
Page 278: =et  irr taot=et muap=et ewa=et ---> COMMENT
Page 278: =kin  vol taot=kin muap=kin ewa=kin ---> COMMENT
Page 278: =nin  neg taot=nin muap=nin ewa=nin ---> COMMENT
Page 278: =in  proh taot=in muap=in ewa=in ---> COMMENT
Page 278: imperative taot=te muap=te ewa=te ---> COMMENT
Page 278: A sizeable minority of Kalamang verbs, 185 out of 650 in the corpus, are vowel- ---> COMMENT
Page 452: In (46), the speaker turns  adeh  int.pej into a verb while scolding their child ---> COMMENT
Page 452: Some  is used for encouragement, often in a slightly annoyed fashion, when ---> TRANSLATION
Page 452: Another interjection with a similar function to  some  is  mera , which is used ---> COMMENT

In [102]:
missing_parrallel_lines_filtered

[{'page_num': 188,
  'bline': {'page_num': 188,
   'line_no': 1,
   'text': 'c.  kor kasir',
   'bbox': (99.95100402832031,
    np.float64(78.87025451660156),
    152.2000274658203,
    91.30663299560547),
   'line': {'text': 'c.  kor kasir',
    'spans': [{'text': 'c.',
      'x0': 99.95100402832031,
      'y0': 78.87025451660156,
      'x1': 107.02009582519531,
      'y1': 91.30663299560547,
      'font': 'LibertinusSerif-Regular',
      'size': 10.909099578857422,
      'block': {'number': 1,
       'type': 0,
       'bbox': (99.0999984741211,
        78.87025451660156,
        156.53094482421875,
        165.2106475830078),
       'lines': [{'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'c.',
           'origin': (99.95100402832031, 88.62299346923828),
           'bbox': (99.95100402832031,
            78.87025451660156,
            107.02009582519531,
            91.30663299560547)},
          {'size': 10.909099578857422,
           'flags': 6,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Italic',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': ' kor',
           'origin': (107.02009582519531, 88.62299346923828),
           'bbox': (107.02009582519531,
            78.87025451660156,
            128.1127471923828,
            91.30663299560547)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (99.95100402832031,
          78.87025451660156,
          128.1127471923828,
          91.30663299560547)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'leg',
           'origin': (114.04000091552734, 102.1719970703125),
           'bbox': (114.04000091552734,
            92.41926574707031,
            127.25092315673828,
            104.85563659667969)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (114.04000091552734,
          92.41926574707031,
          127.25092315673828,
          104.85563659667969)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 6,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Italic',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'kasir',
           'origin': (130.83999633789062, 88.62299346923828),
           'bbox': (130.83999633789062,
            78.87025451660156,
            152.2000274658203,
            91.30663299560547)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (130.83999633789062,
          78.87025451660156,
          152.2000274658203,
          91.30663299560547)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'joint',
           'origin': (130.83999633789062, 102.1719970703125),
           'bbox': (130.83999633789062,
            92.41926574707031,
            151.62184143066406,
            104.85563659667969)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (130.83999633789062,
          92.41926574707031,
          151.62184143066406,
          104.85563659667969)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': '‘ankle’',
           'origin': (113.16699981689453, 117.55499267578125),
           'bbox': (113.16699981689453,
            107.80226135253906,
            143.00338745117188,
            120.23863220214844)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (113.16699981689453,
          107.80226135253906,
          143.00338745117188,
          120.23863220214844)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'd.',
           'origin': (99.0999984741211, 133.59500122070312),
           'bbox': (99.0999984741211,
            123.84226989746094,
            107.02001190185547,
            136.2786407470703)},
          {'size': 10.909099578857422,
           'flags': 6,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Italic',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': ' kor-pak',
           'origin': (107.02001190185547, 133.59500122070312),
           'bbox': (107.02001190185547,
            123.84226989746094,
            147.6836700439453,
            136.2786407470703)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (99.0999984741211,
          123.84226989746094,
          147.6836700439453,
          136.2786407470703)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'leg-moon',
           'origin': (114.04000091552734, 147.1439971923828),
           'bbox': (114.04000091552734,
            137.39126586914062,
            156.53094482421875,
            149.82763671875)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (114.04000091552734,
          137.39126586914062,
          156.53094482421875,
          149.82763671875)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': '‘knee’',
           'origin': (113.16699981689453, 162.52700805664062),
           'bbox': (113.16699981689453,
            152.77427673339844,
            140.09066772460938,
            165.2106475830078)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (113.16699981689453,
          152.77427673339844,
          140.09066772460938,
          165.2106475830078)}]}},
     {'text': ' kor',
      'x0': 107.02009582519531,
      'y0': 78.87025451660156,
      'x1': 128.1127471923828,
      'y1': 91.30663299560547,
      'font': 'LibertinusSerif-Italic',
      'size': 10.909099578857422,
      'block': {'number': 1,
       'type': 0,
       'bbox': (99.0999984741211,
        78.87025451660156,
        156.53094482421875,
        165.2106475830078),
       'lines': [{'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'c.',
           'origin': (99.95100402832031, 88.62299346923828),
           'bbox': (99.95100402832031,
            78.87025451660156,
            107.02009582519531,
            91.30663299560547)},
          {'size': 10.909099578857422,
           'flags': 6,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Italic',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': ' kor',
           'origin': (107.02009582519531, 88.62299346923828),
           'bbox': (107.02009582519531,
            78.87025451660156,
            128.1127471923828,
            91.30663299560547)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (99.95100402832031,
          78.87025451660156,
          128.1127471923828,
          91.30663299560547)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'leg',
           'origin': (114.04000091552734, 102.1719970703125),
           'bbox': (114.04000091552734,
            92.41926574707031,
            127.25092315673828,
            104.85563659667969)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (114.04000091552734,
          92.41926574707031,
          127.25092315673828,
          104.85563659667969)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 6,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Italic',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'kasir',
           'origin': (130.83999633789062, 88.62299346923828),
           'bbox': (130.83999633789062,
            78.87025451660156,
            152.2000274658203,
            91.30663299560547)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (130.83999633789062,
          78.87025451660156,
          152.2000274658203,
          91.30663299560547)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'joint',
           'origin': (130.83999633789062, 102.1719970703125),
           'bbox': (130.83999633789062,
            92.41926574707031,
            151.62184143066406,
            104.85563659667969)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (130.83999633789062,
          92.41926574707031,
          151.62184143066406,
          104.85563659667969)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': '‘ankle’',
           'origin': (113.16699981689453, 117.55499267578125),
           'bbox': (113.16699981689453,
            107.80226135253906,
            143.00338745117188,
            120.23863220214844)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (113.16699981689453,
          107.80226135253906,
          143.00338745117188,
          120.23863220214844)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'd.',
           'origin': (99.0999984741211, 133.59500122070312),
           'bbox': (99.0999984741211,
            123.84226989746094,
            107.02001190185547,
            136.2786407470703)},
          {'size': 10.909099578857422,
           'flags': 6,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Italic',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': ' kor-pak',
           'origin': (107.02001190185547, 133.59500122070312),
           'bbox': (107.02001190185547,
            123.84226989746094,
            147.6836700439453,
            136.2786407470703)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (99.0999984741211,
          123.84226989746094,
          147.6836700439453,
          136.2786407470703)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'leg-moon',
           'origin': (114.04000091552734, 147.1439971923828),
           'bbox': (114.04000091552734,
            137.39126586914062,
            156.53094482421875,
            149.82763671875)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (114.04000091552734,
          137.39126586914062,
          156.53094482421875,
          149.82763671875)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': '‘knee’',
           'origin': (113.16699981689453, 162.52700805664062),
           'bbox': (113.16699981689453,
            152.77427673339844,
            140.09066772460938,
            165.2106475830078)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (113.16699981689453,
          152.77427673339844,
          140.09066772460938,
          165.2106475830078)}]}},
     {'text': 'kasir',
      'x0': 130.83999633789062,
      'y0': 78.87025451660156,
      'x1': 152.2000274658203,
      'y1': 91.30663299560547,
      'font': 'LibertinusSerif-Italic',
      'size': 10.909099578857422,
      'block': {'number': 1,
       'type': 0,
       'bbox': (99.0999984741211,
        78.87025451660156,
        156.53094482421875,
        165.2106475830078),
       'lines': [{'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'c.',
           'origin': (99.95100402832031, 88.62299346923828),
           'bbox': (99.95100402832031,
            78.87025451660156,
            107.02009582519531,
            91.30663299560547)},
          {'size': 10.909099578857422,
           'flags': 6,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Italic',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': ' kor',
           'origin': (107.02009582519531, 88.62299346923828),
           'bbox': (107.02009582519531,
            78.87025451660156,
            128.1127471923828,
            91.30663299560547)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (99.95100402832031,
          78.87025451660156,
          128.1127471923828,
          91.30663299560547)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'leg',
           'origin': (114.04000091552734, 102.1719970703125),
           'bbox': (114.04000091552734,
            92.41926574707031,
            127.25092315673828,
            104.85563659667969)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (114.04000091552734,
          92.41926574707031,
          127.25092315673828,
          104.85563659667969)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 6,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Italic',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'kasir',
           'origin': (130.83999633789062, 88.62299346923828),
           'bbox': (130.83999633789062,
            78.87025451660156,
            152.2000274658203,
            91.30663299560547)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (130.83999633789062,
          78.87025451660156,
          152.2000274658203,
          91.30663299560547)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'joint',
           'origin': (130.83999633789062, 102.1719970703125),
           'bbox': (130.83999633789062,
            92.41926574707031,
            151.62184143066406,
            104.85563659667969)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (130.83999633789062,
          92.41926574707031,
          151.62184143066406,
          104.85563659667969)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': '‘ankle’',
           'origin': (113.16699981689453, 117.55499267578125),
           'bbox': (113.16699981689453,
            107.80226135253906,
            143.00338745117188,
            120.23863220214844)}],
         'wmode': 0,
         'dir': (1.0, 0.0),
         'bbox': (113.16699981689453,
          107.80226135253906,
          143.00338745117188,
          120.23863220214844)},
        {'spans': [{'size': 10.909099578857422,
           'flags': 4,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Regular',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': 'd.',
           'origin': (99.0999984741211, 133.59500122070312),
           'bbox': (99.0999984741211,
            123.84226989746094,
            107.02001190185547,
            136.2786407470703)},
          {'size': 10.909099578857422,
           'flags': 6,
           'bidi': 0,
           'char_flags': 16,
           'font': 'LibertinusSerif-Italic',
           'color': 0,
           'alpha': 255,
           'ascender': 0.8939999938011169,
           'descender': -0.2460000067949295,
           'text': ' kor-pak',
           'origin': (107.02001190185547, 133.59500122070312),
           'bbox': (107.02001190185547,
            123.84226989746094,
            147.6836700439453,
            136.2786407470703)}],
         'wmode': 0,

In [103]:
final_roles[0]

{'page_num': 20,
 'bline': {'page_num': 20,
  'line_no': 54,
  'text': '(1) hukat kon anggon yuwa',
  'line': {'text': '(1) hukat kon anggon yuwa',
   'spans': [{'text': '(1)',
     'x0': 75.5469970703125,
     'y0': 439.1192626953125,
     'x1': 85.97610473632812,
     'y1': 451.5556335449219,
     'font': 'LibertinusSerif-Regular',
     'size': 10.909099578857422,
     'block': {'number': 9,
      'type': 0,
      'bbox': (75.5469970703125,
       439.1192626953125,
       246.74319458007812,
       480.48760986328125),
      'lines': [{'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': '(1)',
          'origin': (75.5469970703125, 448.87200927734375),
          'bbox': (75.5469970703125,
           439.1192626953125,
           85.97610473632812,
           451.5556335449219)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (75.5469970703125,
         439.1192626953125,
         85.97610473632812,
         451.5556335449219)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'hukat',
          'origin': (96.88500213623047, 448.87200927734375),
          'bbox': (96.88500213623047,
           439.1192626953125,
           122.18319702148438,
           451.5556335449219)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (96.88500213623047,
         439.1192626953125,
         122.18319702148438,
         451.5556335449219)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'jaring_ikan',
          'origin': (96.88500213623047, 462.4219970703125),
          'bbox': (96.88500213623047,
           452.66925048828125,
           147.96141052246094,
           465.1056213378906)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (96.88500213623047,
         452.66925048828125,
         147.96141052246094,
         465.1056213378906)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'kon',
          'origin': (150.68899536132812, 448.87200927734375),
          'bbox': (150.68899536132812,
           439.1192626953125,
           166.51809692382812,
           451.5556335449219)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (150.68899536132812,
         439.1192626953125,
         166.51809692382812,
         451.5556335449219)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'satu',
          'origin': (150.68899536132812, 462.4219970703125),
          'bbox': (150.68899536132812,
           452.66925048828125,
           169.16900634765625,
           465.1056213378906)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (150.68899536132812,
         452.66925048828125,
         169.16900634765625,
         465.1056213378906)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'anggon',
          'origin': (171.89599609375, 448.87200927734375),
          'bbox': (171.89599609375,
           439.1192626953125,
           203.78330993652344,
           451.5556335449219)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (171.89599609375,
         439.1192626953125,
         203.78330993652344,
         451.5556335449219)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'milik_saya',
          'origin': (171.89599609375, 462.4219970703125),
          'bbox': (171.89599609375,
           452.66925048828125,
           220.03785705566406,
           465.1056213378906)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (171.89599609375,
         452.66925048828125,
         220.03785705566406,
         465.1056213378906)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'yuwa',
          'origin': (222.76499938964844, 448.87200927734375),
          'bbox': (222.76499938964844,
           439.1192626953125,
           246.74319458007812,
           451.5556335449219)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (222.76499938964844,
         439.1192626953125,
         246.74319458007812,
         451.5556335449219)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'ini',
          'origin': (222.76499938964844, 462.4219970703125),
          'bbox': (222.76499938964844,
           452.66925048828125,
           234.5904541015625,
           465.1056213378906)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (222.76499938964844,
         452.66925048828125,
         234.5904541015625,
         465.1056213378906)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': '‘jaring ikan milik saya satu ini’',
          'origin': (96.01200103759766, 477.8039855957031),
          'bbox': (96.01200103759766,
           468.0512390136719,
           234.415771484375,
           480.48760986328125)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (96.01200103759766,
         468.0512390136719,
         234.415771484375,
         480.48760986328125)}]}},
    {'text': 'hukat',
     'x0': 96.88500213623047,
     'y0': 439.1192626953125,
     'x1': 122.18319702148438,
     'y1': 451.5556335449219,
     'font': 'LibertinusSerif-Italic',
     'size': 10.909099578857422,
     'block': {'number': 9,
      'type': 0,
      'bbox': (75.5469970703125,
       439.1192626953125,
       246.74319458007812,
       480.48760986328125),
      'lines': [{'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': '(1)',
          'origin': (75.5469970703125, 448.87200927734375),
          'bbox': (75.5469970703125,
           439.1192626953125,
           85.97610473632812,
           451.5556335449219)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (75.5469970703125,
         439.1192626953125,
         85.97610473632812,
         451.5556335449219)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'hukat',
          'origin': (96.88500213623047, 448.87200927734375),
          'bbox': (96.88500213623047,
           439.1192626953125,
           122.18319702148438,
           451.5556335449219)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (96.88500213623047,
         439.1192626953125,
         122.18319702148438,
         451.5556335449219)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'jaring_ikan',
          'origin': (96.88500213623047, 462.4219970703125),
          'bbox': (96.88500213623047,
           452.66925048828125,
           147.96141052246094,
           465.1056213378906)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (96.88500213623047,
         452.66925048828125,
         147.96141052246094,
         465.1056213378906)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'kon',
          'origin': (150.68899536132812, 448.87200927734375),
          'bbox': (150.68899536132812,
           439.1192626953125,
           166.51809692382812,
           451.5556335449219)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (150.68899536132812,
         439.1192626953125,
         166.51809692382812,
         451.5556335449219)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'satu',
          'origin': (150.68899536132812, 462.4219970703125),
          'bbox': (150.68899536132812,
           452.66925048828125,
           169.16900634765625,
           465.1056213378906)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (150.68899536132812,
         452.66925048828125,
         169.16900634765625,
         465.1056213378906)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'anggon',
          'origin': (171.89599609375, 448.87200927734375),
          'bbox': (171.89599609375,
           439.1192626953125,
           203.78330993652344,
           451.5556335449219)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (171.89599609375,
         439.1192626953125,
         203.78330993652344,
         451.5556335449219)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'milik_saya',
          'origin': (171.89599609375, 462.4219970703125),
          'bbox': (171.89599609375,
           452.66925048828125,
           220.03785705566406,
           465.1056213378906)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (171.89599609375,
         452.66925048828125,
         220.03785705566406,
         465.1056213378906)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'yuwa',
          'origin': (222.76499938964844, 448.87200927734375),
          'bbox': (222.76499938964844,
           439.1192626953125,
           246.74319458007812,
           451.5556335449219)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (222.76499938964844,
         439.1192626953125,
         246.74319458007812,
         451.5556335449219)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'ini',
          'origin': (222.76499938964844, 462.4219970703125),
          'bbox': (222.76499938964844,
           452.66925048828125,
           234.5904541015625,
           465.1056213378906)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (222.76499938964844,
         452.66925048828125,
         234.5904541015625,
         465.1056213378906)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': '‘jaring ikan milik saya satu ini’',
          'origin': (96.01200103759766, 477.8039855957031),
          'bbox': (96.01200103759766,
           468.0512390136719,
           234.415771484375,
           480.48760986328125)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (96.01200103759766,
         468.0512390136719,
         234.415771484375,
         480.48760986328125)}]}},
    {'text': 'kon',
     'x0': 150.68899536132812,
     'y0': 439.1192626953125,
     'x1': 166.51809692382812,
     'y1': 451.5556335449219,
     'font': 'LibertinusSerif-Italic',
     'size': 10.909099578857422,
     'block': {'number': 9,
      'type': 0,
      'bbox': (75.5469970703125,
       439.1192626953125,
       246.74319458007812,
       480.48760986328125),
      'lines': [{'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': '(1)',
          'origin': (75.5469970703125, 448.87200927734375),
          'bbox': (75.5469970703125,
           439.1192626953125,
           85.97610473632812,
           451.5556335449219)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (75.5469970703125,
         439.1192626953125,
         85.97610473632812,
         451.5556335449219)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'hukat',
          'origin': (96.88500213623047, 448.87200927734375),
          'bbox': (96.88500213623047,
           439.1192626953125,
           122.18319702148438,
           451.5556335449219)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (96.88500213623047,
         439.1192626953125,
         122.18319702148438,
         451.5556335449219)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'jaring_ikan',
          'origin': (96.88500213623047, 462.4219970703125),
          'bbox': (96.88500213623047,
           452.66925048828125,
           147.96141052246094,
           465.1056213378906)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (96.88500213623047,
         452.66925048828125,
         147.96141052246094,
         465.1056213378906)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'kon',
          'origin': (150.68899536132812, 448.87200927734375),
          'bbox': (150.68899536132812,
           439.1192626953125,
           166.51809692382812,
           451.5556335449219)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (150.68899536132812,
         439.1192626953125,
         166.51809692382812,
         451.5556335449219)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'satu',
          'origin': (150.68899536132812, 462.4219970703125),
          'bbox': (150.68899536132812,
           452.66925048828125,
           169.16900634765625,
           465.1056213378906)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (150.68899536132812,
         452.66925048828125,
         169.16900634765625,
         465.1056213378906)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Italic',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'anggon',
          'origin': (171.89599609375, 448.87200927734375),
          'bbox': (171.89599609375,
           439.1192626953125,
           203.78330993652344,
           451.5556335449219)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (171.89599609375,
         439.1192626953125,
         203.78330993652344,
         451.5556335449219)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 4,
          'bidi': 0,
          'char_flags': 16,
          'font': 'LibertinusSerif-Regular',
          'color': 0,
          'alpha': 255,
          'ascender': 0.8939999938011169,
          'descender': -0.2460000067949295,
          'text': 'milik_saya',
          'origin': (171.89599609375, 462.4219970703125),
          'bbox': (171.89599609375,
           452.66925048828125,
           220.03785705566406,
           465.1056213378906)}],
        'wmode': 0,
        'dir': (1.0, 0.0),
        'bbox': (171.89599609375,
         452.66925048828125,
         220.03785705566406,
         465.1056213378906)},
       {'spans': [{'size': 10.909099578857422,
          'flags': 6,
          'bidi': 0,
          'char_flags': 16,

In [104]:
combined_final_roles = final_roles + missing_parrallel_lines_filtered

In [105]:
len(combined_final_roles)

4322

In [106]:
# Save file
with open("kalamang_combined_final_roles.json","w",encoding="utf-8") as f:
    json.dump(combined_final_roles,f)

In [253]:
print(combined_final_roles[0].keys())
print(combined_final_roles[0]["bline"].keys())
print(combined_final_roles[0]["bline"]["line"].keys())

dict_keys(['page_num', 'bline', 'role'])
dict_keys(['page_num', 'line_no', 'text', 'line', 'bbox', 'start'])
dict_keys(['text', 'spans', 'x0', 'y0', 'x1', 'y1', 'span_count', 'common_font_size', 'common_font_style'])

In [254]:
print(missing_parrallel_lines_filtered[0].keys())
print(missing_parrallel_lines_filtered[0]["bline"].keys())

dict_keys(['page_num', 'bline', 'role'])
dict_keys(['page_num', 'line_no', 'text', 'bbox', 'line', 'start'])

In [281]:
prev_roles = []
prev_line_no = -1000
prev_page_no = -1
filter_indices = []
block_indices = []


i = 0
while i < len(combined_final_roles):
    row = combined_final_roles[i]
    line_no = row["bline"]["line_no"] if "line_no" in row["bline"] else None
    page_no = row["page_num"]
    if line_no == prev_line_no + 1:
        prev_roles.append(row["role"])
        prev_line_no = line_no
        prev_page_no = page_no
        block_indices.append(i)
        
    else:
        # new block. Check the last block 
        if prev_roles!=[]: 
            #print(prev_page_no,prev_roles)
            if all(r == "SOURCE" or r=="COMMENT" for r in prev_roles):
                print("FILTERING BLOCK INDICES:", block_indices)
                filter_indices.extend(block_indices)
            elif "GLOSS" in prev_roles:
                double_gloss_found = False
                # Check for double GLOSS appearing consecutively
                for j in range(1,len(prev_roles)):
                    if prev_roles[j]=="GLOSS" and prev_roles[j-1]=="GLOSS":
                        print("DOUBLE GLOSS")
                        prev_roles[j-1] = "SOURCE"
                        double_gloss_found = True
                        #filter_indices.extend(block_indices)
                        #break
                   
                # Change the roles in combined_final_roles
                if double_gloss_found:
                    print(prev_roles)
                    for j,block_idx in enumerate(block_indices):
                        combined_final_roles[block_idx]["role"] = prev_roles[j]
                        print(f"Changing role at index {block_idx} to {prev_roles[j]}")
            elif "TRANSLATION" in prev_roles and "GLOSS" not in prev_roles and prev_page_no not in [443,446]:
                

                # Check for double source and change one to gloss
                double_source_found = False
                print(prev_page_no,prev_roles)
                for j in range(1,len(prev_roles)):
                    if prev_roles[j]=="SOURCE" and prev_roles[j-1]=="SOURCE":
                        print("DOUBLE SOURCE")
                        prev_roles[j] = "GLOSS"
                        double_source_found = True
                        #filter_indices.extend(block_indices)
                        #break
                if double_source_found:
                    print(prev_roles)
                    for j,block_idx in enumerate(block_indices):
                        
                        combined_final_roles[block_idx]["role"] = prev_roles[j]
                        #print(f"Changing role at index {block_idx} to {prev_roles[j]}")

        block_indices = []
        prev_line_no = line_no
        prev_page_no = page_no
        prev_roles = [row["role"]]
        block_indices.append(i)

    #print(f"Page {page_no}, Line {line_no}: {row['bline']['text']} --> {row['role']}")
    
    i+=1

22 ['SOURCE', 'SOURCE', 'TRANSLATION', 'SOURCE', 'SOURCE', 'TRANSLATION', 'SOURCE', 'SOURCE', 'TRANSLATION']
DOUBLE SOURCE
DOUBLE SOURCE
DOUBLE SOURCE
['SOURCE', 'GLOSS', 'TRANSLATION', 'SOURCE', 'GLOSS', 'TRANSLATION', 'SOURCE', 'GLOSS', 'TRANSLATION']
FILTERING BLOCK INDICES: [47, 48, 49, 50, 51, 52, 53, 54]
FILTERING BLOCK INDICES: [55]
FILTERING BLOCK INDICES: [132, 133, 134, 135]
FILTERING BLOCK INDICES: [238, 239, 240]
FILTERING BLOCK INDICES: [241, 242, 243]
FILTERING BLOCK INDICES: [244]
FILTERING BLOCK INDICES: [273, 274, 275, 276, 277, 278, 279, 280]
FILTERING BLOCK INDICES: [547, 548, 549, 550, 551]
179 ['SOURCE', 'SOURCE', 'TRANSLATION']
DOUBLE SOURCE
['SOURCE', 'GLOSS', 'TRANSLATION']
FILTERING BLOCK INDICES: [591, 592, 593, 594, 595, 596]
183 ['SOURCE', 'TRANSLATION', 'SOURCE', 'TRANSLATION', 'SOURCE', 'TRANSLATION', 'SOURCE', 'TRANSLATION']
FILTERING BLOCK INDICES: [619, 620]
FILTERING BLOCK INDICES: [691, 692, 693]
FILTERING BLOCK INDICES: [703, 704]
FILTERING BLOCK INDICES: [705, 706]
FILTERING BLOCK INDICES: [707, 708]
FILTERING BLOCK INDICES: [709, 710]
FILTERING BLOCK INDICES: [811, 812, 813, 814, 815, 816, 817]
203 ['SOURCE', 'SOURCE', 'TRANSLATION']
DOUBLE SOURCE
['SOURCE', 'GLOSS', 'TRANSLATION']
FILTERING BLOCK INDICES: [962, 963]
FILTERING BLOCK INDICES: [1126, 1127, 1128]
229 ['SOURCE', 'TRANSLATION']
229 ['SOURCE', 'TRANSLATION']
FILTERING BLOCK INDICES: [1442, 1443, 1444]
FILTERING BLOCK INDICES: [1761, 1762, 1763, 1764, 1765, 1766]
FILTERING BLOCK INDICES: [1767, 1768]
FILTERING BLOCK INDICES: [1769, 1770]
FILTERING BLOCK INDICES: [1771, 1772, 1773]
FILTERING BLOCK INDICES: [1823]
FILTERING BLOCK INDICES: [1963, 1964, 1965, 1966, 1967, 1968]
FILTERING BLOCK INDICES: [1969, 1970, 1971, 1972, 1973, 1974]
FILTERING BLOCK INDICES: [1983]
FILTERING BLOCK INDICES: [2342, 2343, 2344, 2345, 2346, 2347, 2348]
FILTERING BLOCK INDICES: [2762]
FILTERING BLOCK INDICES: [3150]
FILTERING BLOCK INDICES: [3160, 3161, 3162, 3163]
FILTERING BLOCK INDICES: [3188, 3189, 3190, 3191]
229 ['SOURCE', 'TRANSLATION', 'SOURCE', 'TRANSLATION', 'SOURCE', 'TRANSLATION', 'TRANSLATION', 'SOURCE', 'TRANSLATION']
229 ['SOURCE', 'TRANSLATION', 'SOURCE', 'TRANSLATION', 'SOURCE', 'TRANSLATION']

In [284]:
# Render the final combined roles on the pdf
print("Opening PDF file...")
doc = pymupdf.open(pdf_file_path)
print("PDF file opened successfully.")
# Render the pdf with the lines extracted with bounding boxes

for i,row in enumerate(combined_final_roles):
    if i in filter_indices:
        continue

    text = row["bline"]["text"].strip()
    if "to chew betel" in text.lower():
        print("Skipped line with 'to chew betel'")
        continue
    page_num = row["page_num"]
    page = doc[page_num - 1]
    bbox = row["bline"]["bbox"]
    rect = pymupdf.Rect(bbox)
    role = row["role"]
    if role == "SOURCE":
        color = (0, 0, 1)  # Blue
    elif role == "GLOSS":
        color = (0, 1, 0)  # Green
    elif role == "TRANSLATION":
        color = (1, 0, 0)  # Red
    else:
        color = (1, 1, 0)  # Yellow for COMMENT

    page.draw_rect(rect, color=color, width=0.5)

doc.save("output_with_combined_final_roles.pdf")
doc.close()

Opening PDF file...
PDF file opened successfully.
Skipped line with 'to chew betel'

In [285]:
combined_final_roles_filtered = [row for i,row in enumerate(combined_final_roles) if i not in filter_indices ]
print(len(combined_final_roles))
combined_final_roles_filtered = [row for row in combined_final_roles_filtered if "to chew betel" not in row["bline"]["text"].lower()]
print(len(combined_final_roles_filtered))
combined_final_roles_filtered = [row for row in combined_final_roles_filtered if row["role"]!="COMMENT"]
print(len(combined_final_roles_filtered))

4355
4243
4224

In [286]:
# Store final filtered roles
with open("combined_final_roles_filtered.json","w",encoding="utf-8") as f:
    json.dump(combined_final_roles_filtered,f)

# Parallel sentence classifier

In [39]:
import json
import pandas as pd

def load_and_flatten(json_path):
    with open(json_path, "r", encoding="utf-8") as f:
        rows = json.load(f)

    data = []
    for row in rows:
        b = row["bline"]
        data.append({
            "page": row["page_num"],
            "line_no": b["line_no"],
            "text": b["text"],
            "x0": b["bbox"][0],
            "y0": b["bbox"][1],
            "x1": b["bbox"][2],
            "y1": b["bbox"][3],
            "width": b["bbox"][2] - b["bbox"][0],
            "height": b["bbox"][3] - b["bbox"][1],
            "role": row["role"]
        })
         

    return data

curated_data = load_and_flatten("combined_final_roles_filtered.json")
curated_lookup = {}
for row in curated_data:

    curated_lookup[(row["page"], row["text"])] = row["role"]

In [40]:
print(len(curated_lookup))
print(len(curated_data))

4213
4224

In [41]:
# Load the entire line table with role as OTHER
all_data = []
count = 0
all_lines_count = 0
for row in all_merged_lines:
    
    lines = row["lines"]
    for line_no,line in enumerate(lines):
        #print(line.keys())
        all_lines_count += 1
        role = "OTHER"
        curated_row = curated_lookup.get((row["page_num"], line["text"]))
        if curated_row is not None:
            role = curated_row
            
            count += 1
            
        all_data.append({
            "page": row["page_num"],
            "line_no": line_no,
            "text": line["text"],
            "x0": line["x0"],
            "y0": line["y0"],
            "x1": line["x1"],
            "y1": line["y1"],
            "width": line["x1"] - line["x0"],
            "height": line["y1"] - line["y0"],
            "role": role
        })

print("Number of curated lines skipped:", count)
print("Total lines processed:", all_lines_count)
print("Length of curated data:", len(curated_data))

Number of curated lines skipped: 0
Total lines processed: 20150
Length of curated data: 4224

In [42]:
print(len(all_data))

20150

In [43]:
df = pd.DataFrame(all_data)
df.head()

,page,line_no,text,x0,y0,x1,y1,width,height,role
0,1,0,A grammar of,46.354000,50.835377,351.912201,100.382675,305.558201,49.547298,OTHER
1,1,1,Tuatschin,44.818001,99.733368,257.772308,149.280670,212.954308,49.547302,OTHER
2,1,2,A Sursilvan Romansh dialect,46.354000,167.793213,354.761932,191.613998,308.407932,23.820786,OTHER
3,1,3,Philippe Maurer-Cecchini,46.354000,221.051514,311.559509,249.445038,265.205509,28.393524,OTHER
4,1,4,Comprehensive Grammar Library 3 language science,46.354000,592.548401,431.578400,606.221252,385.224400,13.672852,OTHER

In [339]:
df["center_x"] = (df["x0"] + df["x1"]) / 2
df["center_y"] = (df["y0"] + df["y1"]) / 2
df["area"] = df["width"] * df["height"]
df["aspect_ratio"] = df["width"] / (df["height"] + 1e-6)
df.head()

,page,line_no,text,x0,y0,x1,y1,width,height,role,center_x,center_y,area,aspect_ratio
0,1,0,A grammar of,46.354000,50.835377,351.912201,100.382675,305.558201,49.547298,OTHER,199.133101,75.609026,15139.583365,6.167000
1,1,1,Kalamang,46.354000,99.733368,269.415955,149.280670,223.061954,49.547302,OTHER,157.884977,124.507019,11052.118079,4.502000
2,1,2,Eline Visser,46.354000,183.008514,169.292999,211.402039,122.938999,28.393524,OTHER,107.823500,197.205276,3490.671445,4.329825
3,1,3,Comprehensive Grammar Library 4 language science,46.354000,592.548401,431.578400,606.221252,385.224400,13.672852,OTHER,238.966200,599.384827,5267.116034,28.174399
4,1,4,press,403.896912,606.764160,423.339966,614.754333,19.443054,7.990173,OTHER,413.618439,610.759247,155.353373,2.433370

In [343]:
from sklearn.model_selection import train_test_split

# === Your split ===
train_df, test_df = train_test_split(
    df,
    test_size=0.15,
    random_state=42,
    stratify=df["role"]
)

print("Training set size:", len(train_df))
print("Test set size:", len(test_df))

Training set size: 16231
Test set size: 2865

In [346]:
from catboost import CatBoostClassifier, Pool


# === Features ===
text_features = ["text"]
num_features = [
    "page","line_no","x0","y0","x1","y1",
    "width","height","center_x","center_y",
    "area","aspect_ratio"
]

feature_cols = num_features + text_features

# CatBoost expects column indices for text features
text_feature_indices = [feature_cols.index("text")]

# === Pools ===
train_pool = Pool(
    data=train_df[feature_cols],
    label=train_df["role"],
    text_features=text_feature_indices
)

test_pool = Pool(
    data=test_df[feature_cols],
    label=test_df["role"],
    text_features=text_feature_indices
)

# === Model ===
model = CatBoostClassifier(
    iterations=100,
    depth=8,
    learning_rate=0.05,
    loss_function="MultiClass",
    random_seed=42,
    eval_metric="TotalF1",
    task_type="CPU"
)

model.fit(train_pool, eval_set=test_pool, verbose=50)

0:	learn: 0.9236584	test: 0.9363879	best: 0.9363879 (0)	total: 877ms	remaining: 1m 26s
50:	learn: 0.9680546	test: 0.9700091	best: 0.9700091 (48)	total: 46.1s	remaining: 44.3s
99:	learn: 0.9717044	test: 0.9722861	best: 0.9730120 (77)	total: 1m 30s	remaining: 0us

bestTest = 0.9730120359
bestIteration = 77

Shrink model to first 78 iterations.

In [347]:
# Store the model
model.save_model("kalamang_line_role_classifier.cbm")

In [348]:
# Read different grammar book
new_pdf_file_path = "grammar_books/sursilvan_romansh.pdf"

# Load doc
print("Opening new PDF file...")
new_doc = pymupdf.open(new_pdf_file_path)
print("New PDF file opened successfully.")

Opening new PDF file...
New PDF file opened successfully.

In [349]:
all_merged_lines_romansh = []
for page in new_doc:
    page_num = page.number + 1
    
    merged_lines = extract_visual_lines(page)
    if merged_lines is None:
        continue
    all_merged_lines_romansh.append({
        "page_num": page_num,
        "lines": merged_lines
    })

In [350]:
# prepare data for prediction
all_data_romansh = []
for row in all_merged_lines_romansh:
    lines = row["lines"]
    for line_no,line in enumerate(lines):
        all_data_romansh.append({
            "page": row["page_num"],
            "line_no": line_no,
            "text": line["text"],
            "x0": line["x0"],
            "y0": line["y0"],
            "x1": line["x1"],
            "y1": line["y1"],
            "width": line["x1"] - line["x0"],
            "height": line["y1"] - line["y0"],
            "role": "OTHER"  # placeholder
        })
df_romansh = pd.DataFrame(all_data_romansh)
df_romansh["center_x"] = (df_romansh["x0"] + df_romansh["x1"]) / 2
df_romansh["center_y"] = (df_romansh["y0"] + df_romansh["y1"]) / 2
df_romansh["area"] = df_romansh["width"] * df_romansh["height"]
df_romansh["aspect_ratio"] = df_romansh["width"] / (df_romansh["height"] + 1e-6)
df_romansh.head()

,page,line_no,text,x0,y0,x1,y1,width,height,role,center_x,center_y,area,aspect_ratio
0,1,0,A grammar of,46.354000,50.835377,351.912201,100.382675,305.558201,49.547298,OTHER,199.133101,75.609026,15139.583365,6.167000
1,1,1,Tuatschin,44.818001,99.733368,257.772308,149.280670,212.954308,49.547302,OTHER,151.295155,124.507019,10551.311441,4.298000
2,1,2,A Sursilvan Romansh dialect,46.354000,167.793213,354.761932,191.613998,308.407932,23.820786,OTHER,200.557966,179.703606,7346.519208,12.947009
3,1,3,Philippe Maurer-Cecchini,46.354000,221.051514,311.559509,249.445038,265.205509,28.393524,OTHER,178.956755,235.248276,7530.119035,9.340352
4,1,4,Comprehensive Grammar Library 3 language science,46.354000,592.548401,431.578400,606.221252,385.224400,13.672852,OTHER,238.966200,599.384827,5267.116034,28.174399

In [355]:
# Run inference
preds = model.predict(df_romansh[feature_cols])
probs = model.predict_proba(df_romansh[feature_cols])
print(preds)

[['OTHER']
 ['OTHER']
 ['OTHER']
 ...
 ['OTHER']
 ['OTHER']
 ['OTHER']]

In [356]:
df_romansh["predicted_role"] = preds.ravel()
df_romansh["prediction_confidence"] = probs.max(axis=1)
df_romansh.head()

,page,line_no,text,x0,y0,x1,y1,width,height,role,center_x,center_y,area,aspect_ratio,predicted_role,prediction_confidence
0,1,0,A grammar of,46.354000,50.835377,351.912201,100.382675,305.558201,49.547298,OTHER,199.133101,75.609026,15139.583365,6.167000,OTHER,0.974587
1,1,1,Tuatschin,44.818001,99.733368,257.772308,149.280670,212.954308,49.547302,OTHER,151.295155,124.507019,10551.311441,4.298000,OTHER,0.967829
2,1,2,A Sursilvan Romansh dialect,46.354000,167.793213,354.761932,191.613998,308.407932,23.820786,OTHER,200.557966,179.703606,7346.519208,12.947009,OTHER,0.974936
3,1,3,Philippe Maurer-Cecchini,46.354000,221.051514,311.559509,249.445038,265.205509,28.393524,OTHER,178.956755,235.248276,7530.119035,9.340352,OTHER,0.969545
4,1,4,Comprehensive Grammar Library 3 language science,46.354000,592.548401,431.578400,606.221252,385.224400,13.672852,OTHER,238.966200,599.384827,5267.116034,28.174399,OTHER,0.980075

In [363]:
import fitz

def render_predictions_with_labels(pdf_path, df_pred, output_path):
    doc = fitz.open(pdf_path)

    for page_num in range(len(doc)):
        page = doc[page_num]
        subset = df_pred[df_pred.page == page_num + 1]

        for _, row in subset.iterrows():
            bbox = fitz.Rect(row["x0"], row["y0"], row["x1"], row["y1"])

            # Colors
            role = row["predicted_role"]
            if role == "SOURCE":
                color = (0, 0, 1)
            elif role == "GLOSS":
                color = (0, 1, 0)
            elif role == "TRANSLATION":
                color = (1, 0, 0)
            else:
                color = (0.7, 0.7, 0.7)

            conf = float(row["prediction_confidence"])
            conf = max(0, min(1, conf))

            # Border thickness
            thickness = 0.2 + 1.8 * conf
            page.draw_rect(bbox, color=color, width=thickness)

            # Add small label
            label_text = f"{conf:.2f}"
            text_pos = fitz.Point(row["x1"] - 20, row["y0"] + 2)

            page.insert_text(
                text_pos,
                label_text,
                fontsize=6,
                color=(0, 0, 0),         # black text
                fill_opacity=0.8
            )

    doc.save(output_path)
    doc.close()
    print("Saved:", output_path)

render_predictions_with_labels(new_pdf_file_path, df_romansh, "sursilvan_romansh_with_predictions.pdf")

Saved: sursilvan_romansh_with_predictions.pdf

In [364]:
df_romansh.to_csv("sursilvan_romansh_line_roles_predictions.csv", index=False)

In [365]:
# Load the active learning dataset
import json
corrected_labels_file = "sursilvan_romansh_corrected_labels.json"

with open(corrected_labels_file, "r", encoding="utf-8") as f:
    corrected_data = json.load(f)

corrected_data

FileNotFoundError: [Errno 2] No such file or directory: 'sursilvan_romansh_corrected_labels.json'

# Test 2

In [3]:

import pymupdf
import json

with open("kalamang_combined_final_roles.json","r",encoding="utf-8") as f:
    combined_final_roles = json.load(f)

In [4]:
pdf_file_path = "grammar_books/kalamang.pdf"

In [5]:
print("Opening PDF file...")
new_doc = pymupdf.open(pdf_file_path)
print("PDF file opened successfully.")

Opening PDF file...
PDF file opened successfully.

In [6]:
import json
import pandas as pd

def load_and_flatten(json_path):
    with open(json_path, "r", encoding="utf-8") as f:
        rows = json.load(f)

    data = []
    for row in rows:
        b = row["bline"]
        data.append({
            "page": row["page_num"],
            "line_no": b["line_no"],
            "text": b["text"],
            "x0": b["bbox"][0],
            "y0": b["bbox"][1],
            "x1": b["bbox"][2],
            "y1": b["bbox"][3],
            "width": b["bbox"][2] - b["bbox"][0],
            "height": b["bbox"][3] - b["bbox"][1],
            "role": row["role"]
        })
         

    return data

curated_data = load_and_flatten("kalamang_combined_final_roles.json")
curated_lookup = {}
for row in curated_data:

    curated_lookup[(row["page"], row["text"])] = row["role"]

In [11]:
# Create line level data to train model
all_merged_lines = []
for page in new_doc:
    page_num = page.number + 1
    
    merged_lines = extract_visual_lines(page)
    if merged_lines is None:
        continue
    all_merged_lines.append({
        "page_num": page_num,
        "lines": merged_lines
    })

# prepare data for prediction
all_data = []
for row in all_merged_lines:
    lines = row["lines"]
    for line_no,line in enumerate(lines):
        all_data.append({
            "page": row["page_num"],
            "line_no": line_no,
            "text": line["text"],
            "x0": line["x0"],
            "y0": line["y0"],
            "x1": line["x1"],
            "y1": line["y1"],
            "width": line["x1"] - line["x0"],
            "height": line["y1"] - line["y0"],
            "role": "OTHER"  # placeholder
        })
df = pd.DataFrame(all_data)

In [12]:
df.head()

,page,line_no,text,x0,y0,x1,y1,width,height,role
0,1,0,A grammar of,46.354000,50.835377,351.912201,100.382675,305.558201,49.547298,OTHER
1,1,1,Kalamang,46.354000,99.733368,269.415955,149.280670,223.061954,49.547302,OTHER
2,1,2,Eline Visser,46.354000,183.008514,169.292999,211.402039,122.938999,28.393524,OTHER
3,1,3,Comprehensive Grammar Library 4 language science,46.354000,592.548401,431.578400,606.221252,385.224400,13.672852,OTHER
4,1,4,press,403.896912,606.764160,423.339966,614.754333,19.443054,7.990173,OTHER

In [13]:
text_only_df = df[["text","role","page","line_no"]].copy()
text_only_df.head()

                                               text   role  page  line_no
0                                      A grammar of  OTHER     1        0
1                                          Kalamang  OTHER     1        1
2                                      Eline Visser  OTHER     1        2
3  Comprehensive Grammar Library 4 language science  OTHER     1        3
4                                             press  OTHER     1        4

In [14]:
text_only_df.to_csv("kalamang_text_only_data_for_bert_training.csv",index=False)

In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from datasets import Dataset
from transformers import AutoTokenizer, AutoModel, Trainer, TrainingArguments
import re

In [2]:


MODEL_NAME = "bert-base-multilingual-cased"
MAX_LEN = 128

# ---------------------------------------------------------
# Load your CSV
# ---------------------------------------------------------
df = pd.read_csv("kalamang_text_only_data_for_bert_training.csv").fillna("")
print(df.columns)
df = df.sort_values(["page", "line_no"])

# role is your label column
labels = sorted(df["role"].unique())
label2id = {l:i for i,l in enumerate(labels)}
id2label = {i:l for l,i in label2id.items()}
df["label_id"] = df["role"].map(label2id)

# ---------------------------------------------------------
# Add simple context (prev / next lines)
# ---------------------------------------------------------
prev_lines = []
next_lines = []

for idx in range(len(df)):
    if idx > 0 and df.iloc[idx-1]["page"] == df.iloc[idx]["page"]:
        prev_lines.append(df.iloc[idx-1]["text"])
    else:
        prev_lines.append("")
    if idx < len(df)-1 and df.iloc[idx+1]["page"] == df.iloc[idx]["page"]:
        next_lines.append(df.iloc[idx+1]["text"])
    else:
        next_lines.append("")

df["prev"] = prev_lines
df["next"] = next_lines

df["context_text"] = (
    "[PREV] " + df["prev"] +
    " [CURR] " + df["text"] +
    " [NEXT] " + df["next"]
)

Index(['text', 'role', 'page', 'line_no'], dtype='object')

In [7]:
# ---------------------------------------------------------
# Structural feature extractor (safe across docs)
# ---------------------------------------------------------
def structural_features(line):
    tokens = line.split()
    ascii_chars = sum(c.isascii() for c in line)
    non_ascii = len(line) - ascii_chars

    return {
        "len": len(line),
        "num_tokens": len(tokens),
        "ascii_ratio": ascii_chars / max(1, len(line)),
        "non_ascii": non_ascii,
        "digit_ratio": sum(c.isdigit() for c in line) / max(1, len(line)),
        "has_gloss_markers": int(bool(re.search(r"[=~\-]", line))),
        "token_length_mean": np.mean([len(t) for t in tokens]) if tokens else 0,
        "token_length_std": np.std([len(t) for t in tokens]) if tokens else 0,
    }

feat_list = df["text"].apply(structural_features).tolist()
feat_df = pd.DataFrame(feat_list)
df = pd.concat([df, feat_df], axis=1)

# ---------------------------------------------------------
# Convert to HuggingFace dataset
# ---------------------------------------------------------
dataset = Dataset.from_pandas(df)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize(batch):
    enc = tokenizer(
        batch["context_text"],
        truncation=True,
        padding="max_length",
        max_length=MAX_LEN
    )

    # attach structural features
    for key in ["len", "num_tokens", "ascii_ratio", "non_ascii",
                "digit_ratio", "has_gloss_markers",
                "token_length_mean", "token_length_std"]:
        enc[key] = batch[key]

    return enc

dataset = dataset.map(tokenize, batched=True)
dataset = dataset.rename_column("label_id", "labels")

# Keep only needed tensors
cols = ["input_ids", "attention_mask", "labels",
        "len", "num_tokens", "ascii_ratio", "non_ascii",
        "digit_ratio", "has_gloss_markers", "token_length_mean", "token_length_std"]

dataset.set_format(type="torch", columns=cols)

# ---------------------------------------------------------
# Train/Validation split
# ---------------------------------------------------------
ds = dataset.train_test_split(test_size=0.1)

Map:   0%|          | 0/19096 [00:00<?, ? examples/s]

In [8]:

# ---------------------------------------------------------
# Model: BERT + structural features → MLP
# ---------------------------------------------------------
class LineClassifier(nn.Module):
    def __init__(self, bert_name, num_labels, feat_dim):
        super().__init__()
        self.bert = AutoModel.from_pretrained(bert_name)
        hidden = self.bert.config.hidden_size

        self.classifier = nn.Sequential(
            nn.Linear(hidden + feat_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(256, num_labels)
        )

    def forward(self, input_ids, attention_mask,
                len, num_tokens, ascii_ratio, non_ascii,
                digit_ratio, has_gloss_markers,
                token_length_mean, token_length_std,
                labels=None):

        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        pooled = outputs.pooler_output

        feats = torch.stack([
            len, num_tokens, ascii_ratio, non_ascii, digit_ratio,
            has_gloss_markers.float(), token_length_mean, token_length_std
        ], dim=1)

        combined = torch.cat([pooled, feats], dim=1)
        logits = self.classifier(combined)

        loss = None
        if labels is not None:
            loss = nn.CrossEntropyLoss()(logits, labels)

        return {"loss": loss, "logits": logits}

In [9]:
torch.cuda.empty_cache()

In [10]:
feature_dim = 8
model = LineClassifier(MODEL_NAME, num_labels=len(labels), feat_dim=feature_dim)

# ---------------------------------------------------------
# Trainer
# ---------------------------------------------------------
training_args = TrainingArguments(
    output_dir="stage1_line_classifier",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=4,
)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)
model = model.to(device)

# Move dataset to device


trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=ds["train"],
    eval_dataset=ds["test"],
    tokenizer=tokenizer,
)

trainer.train()
trainer.save_model("stage1_line_classifier_final")

Using device: cuda

C:\Users\Varun\AppData\Local\Temp\ipykernel_33728\3265261300.py:22: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(